const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=null,mode='local',flipped=false,selected=null,pendingPromotion=null,gameTimer=null,accountId=localStorage.getItem('saniChessAccount')||null,me=null,store=null,lastResultKey=null,rematchTimer=null,drawPromptKey=null;
let online={uid:null,roomId:null,side:null,room:null},bot={uid:null,roomId:null,room:null,botKey:null,stake:0};
const START='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const glyph={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
const KN=[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]],KI=[[1,1],[1,0],[1,-1],[0,1],[0,-1],[-1,1],[-1,0],[-1,-1]];
function parseFen(fen){const [pl,side,castling,ep,half,full]=fen.split(/\s+/),b=Array(64).fill(null);let r=7,f=0;for(const c of pl){if(c==='/'){r--;f=0}else if(/[1-8]/.test(c))f+=+c;else b[r*8+f++]=c}return{board:b,side,castling:castling==='-'?'':castling,ep:ep==='-'?null:ep.charCodeAt(0)-97+8*(+ep[1]-1),half:+half,full:+full}}
function file(s){return s%8}function rank(s){return Math.floor(s/8)}function color(p){return p?p===p.toUpperCase()?'w':'b':null}function enemy(c){return c==='w'?'b':'w'}
function attacked(st,s,by){const f=file(s),r=rank(s),pr=r+(by==='w'?-1:1),pc=by==='w'?'P':'p';if(pr>=0&&pr<8)for(const df of[-1,1])if(f+df>=0&&f+df<8&&st.board[pr*8+f+df]===pc)return true;const nk=by==='w'?'N':'n';for(const[dF,dR]of KN){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[R*8+F]===nk)return true}const kk=by==='w'?'K':'k';for(const[dF,dR]of KI){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[R*8+F]===kk)return true}for(const[dF,dR]of[[1,0],[-1,0],[0,1],[0,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[R*8+F];if(p){if(color(p)===by&&'rq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}for(const[dF,dR]of[[1,1],[1,-1],[-1,1],[-1,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[R*8+F];if(p){if(color(p)===by&&'bq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}return false}
function king(st,c){return st.board.findIndex(p=>p===(c==='w'?'K':'k'))}function check(st,c){const k=king(st,c);return k<0||attacked(st,k,enemy(c))}
function clone(s){return{board:s.board.slice(),side:s.side,castling:s.castling,ep:s.ep,half:s.half,full:s.full}}
function pseudo(st){const c=st.side,m=[],add=(f,t,x={})=>m.push({from:f,to:t,...x});for(let from=0;from<64;from++){const p=st.board[from];if(!p||color(p)!==c)continue;const f=file(from),r=rank(from),u=p.toUpperCase();if(u==='P'){const d=c==='w'?1:-1,sr=c==='w'?1:6,pr=c==='w'?7:0,rr=r+d;if(rr>=0&&rr<8){const one=rr*8+f;if(!st.board[one]){if(rr===pr)['Q','R','B','N'].forEach(q=>add(from,one,{promotion:c==='w'?q:q.toLowerCase()}));else add(from,one);if(r===sr){const two=(r+2*d)*8+f;if(!st.board[two])add(from,two)}}for(const df of[-1,1]){const F=f+df;if(F<0||F>7)continue;const to=rr*8+F,t=st.board[to];if(t&&color(t)!==c&&t.toUpperCase()!=='K'){if(rr===pr)['Q','R','B','N'].forEach(q=>add(from,to,{promotion:c==='w'?q:q.toLowerCase()}));else add(from,to)}if(st.ep===to&&st.board[to+(c==='w'?-8:8)]===(c==='w'?'p':'P'))add(from,to,{ep:true})}}}else if(u==='N'){for(const[dF,dR]of KN){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=R*8+F,t=st.board[to];if(!t||color(t)!==c&&t.toUpperCase()!=='K')add(from,to)}}}else if(u==='K'){for(const[dF,dR]of KI){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=R*8+F,t=st.board[to];if(!t||color(t)!==c&&t.toUpperCase()!=='K')add(from,to)}}const rr=c==='w'?0:7;if(from===rr*8+4&&!check(st,c)){const K=c==='w'?'K':'k',Q=c==='w'?'Q':'q';if(st.castling.includes(K)&&st.board[rr*8+7]===(c==='w'?'R':'r')&&!st.board[rr*8+5]&&!st.board[rr*8+6]&&!attacked(st,rr*8+5,enemy(c))&&!attacked(st,rr*8+6,enemy(c)))add(from,rr*8+6,{castle:'K'});if(st.castling.includes(Q)&&st.board[rr*8]===(c==='w'?'R':'r')&&!st.board[rr*8+1]&&!st.board[rr*8+2]&&!st.board[rr*8+3]&&!attacked(st,rr*8+3,enemy(c))&&!attacked(st,rr*8+2,enemy(c)))add(from,rr*8+2,{castle:'Q'})}}else{const ds=u==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:u==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const[dF,dR]of ds){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const to=R*8+F,t=st.board[to];if(!t)add(from,to);else{if(color(t)!==c&&t.toUpperCase()!=='K')add(from,to);break}F+=dF;R+=dR}}}}return m}
function apply(st,m){const n=clone(st),p=n.board[m.from],c=n.side,u=p.toUpperCase(),target=n.board[m.to];n.board[m.from]=null;if(m.ep)n.board[m.to+(c==='w'?-8:8)]=null;n.board[m.to]=m.promotion||p;if(m.castle){const rr=c==='w'?0:7;if(m.castle==='K'){n.board[rr*8+5]=n.board[rr*8+7];n.board[rr*8+7]=null}else{n.board[rr*8+3]=n.board[rr*8];n.board[rr*8]=null}}if(u==='K')n.castling=n.castling.replace(c==='w'?/[KQ]/g:/[kq]/g,'');if(u==='R'){if(m.from===0)n.castling=n.castling.replace('Q','');if(m.from===7)n.castling=n.castling.replace('K','');if(m.from===56)n.castling=n.castling.replace('q','');if(m.from===63)n.castling=n.castling.replace('k','')}if(target?.toUpperCase()==='R'){if(m.to===0)n.castling=n.castling.replace('Q','');if(m.to===7)n.castling=n.castling.replace('K','');if(m.to===56)n.castling=n.castling.replace('q','');if(m.to===63)n.castling=n.castling.replace('k','')}n.ep=null;if(u==='P'&&Math.abs(m.to-m.from)===16)n.ep=(m.from+m.to)/2;n.half=(u==='P'||target||m.ep)?0:n.half+1;if(c==='b')n.full++;n.side=enemy(c);return n}
function legal(st){return pseudo(st).filter(m=>!check(apply(st,m),st.side))}
function squareName(s){return 'abcdefgh'[file(s)]+(rank(s)+1)}
function notation(m,st){const p=st.board[m.from].toUpperCase();if(m.castle)return m.castle==='K'?'O-O':'O-O-O';return `${p==='P'?'':p}${squareName(m.from)}→${squareName(m.to)}${m.promotion?'='+m.promotion.toUpperCase():''}`}
function fmt(ms){ms=Math.max(0,ms);return`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let j={};try{j=await r.json()}catch{}if(!r.ok||!j.ok)throw new Error(j.error||'Ошибка сервера');return j}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').hidden=false}function closeModal(){$('#modal').hidden=true}
function refreshHome(){if(!me)return;$('#connection').textContent=`● ${me.name} • 🪙 ${me.chips}`;$('#connection').title=`${me.rank.name} • ${me.wins} побед • ${me.vip?'VIP':''}`;$$('[data-action]').forEach(b=>b.disabled=false)}
function authActions(){$$('[data-action]').forEach(b=>b.disabled=true);const shop=$('#shopBtn'),profile=$('#profileBtn'),admin=$('#adminBtn'),leader=$('#leaderBtn'),homeShop=$('#shopHome');shop.onclick=e=>{e.preventDefault();e.stopPropagation();openShop()};profile.onclick=e=>{e.preventDefault();e.stopPropagation();profileModal()};admin.onclick=e=>{e.preventDefault();e.stopPropagation();openAdmin()};leader.onclick=e=>{e.preventDefault();e.stopPropagation();openLeaderboard()};homeShop.onclick=e=>{e.preventDefault();e.stopPropagation();openShop()};authenticate()}
async function authenticate(){try{const j=await api('/api/auth',{method:'POST',body:JSON.stringify({id:accountId})});if(j.needsName){openModal(`<div class="auth-card"><div class="auth-logo">♔</div><h2>Добро пожаловать в SANI CHESS</h2><p>Введите никнейм. Новый игрок получает <b>100 000 фишек</b>.</p><input id="firstNick" maxlength="24" placeholder="Ваш никнейм"><button class="primary" id="createAccount">Создать игрока</button></div>`);$('#createAccount').onclick=async()=>{const name=$('#firstNick').value.trim();if(!name)return alert('Введите никнейм');try{const x=await api('/api/auth',{method:'POST',body:JSON.stringify({id:accountId||'',name})});accountId=x.user.id;localStorage.setItem('saniChessAccount',accountId);me=x.user;store=x.store;closeModal();refreshHome()}catch(e){alert(e.message)}};return}me=j.user;store=j.store;accountId=me.id;localStorage.setItem('saniChessAccount',accountId);refreshHome()}catch(e){localStorage.removeItem('saniChessAccount');accountId=null;alert(e.message)}}
function profileModal(){openModal(`<div class="profile"><h2>👤 Профиль</h2><p><b>${escapeHtml(me.name)}</b>${me.vip?' <span class="vip">VIP</span>':''}</p><div class="profile-stat">🪙 <b>${me.chips.toLocaleString('ru-RU')}</b> фишек</div><div class="rank-box"><b>Уровень ${me.rank.level} • ${me.rank.name}</b><span>${me.wins} побед • ${me.losses} поражений • ${me.draws} ничьих</span></div><p>До следующего уровня: ${nextRankText()}</p></div>`)}
function nextRankText(){const r=me.rank;const ranks=[{wins:0,name:'Новичок'},{wins:3,name:'Ученик'},{wins:10,name:'Любитель'},{wins:25,name:'Игрок'},{wins:50,name:'Сильный игрок'},{wins:100,name:'Эксперт'},{wins:250,name:'Мастер'},{wins:500,name:'Гроссмейстер'}];const n=ranks.find(x=>x.wins>me.wins);return n?`${Math.max(0,n.wins-me.wins)} побед до ${n.name}`:'максимальный уровень'}
function stakeValue(id){const n=Math.floor(Number($(id)?.value));return Number.isFinite(n)&&n>=0?n:0}
function botSetup(){const max=me.chips;openModal(`<div class="setup"><h2>🤖 Игра с компьютером</h2><p>Выберите уровень соперника и любую ставку в пределах вашего баланса.</p><div class="bot-grid"><button class="bot-option active" data-bot="kettle"><b>1 • Чайник</b><small>Самый лёгкий • начинающий соперник</small></button><button class="bot-option" data-bot="player"><b>2 • Шпилер</b><small>Нормальный • уверенный игрок</small></button><button class="bot-option" data-bot="maestro"><b>3 • Маэстро</b><small>Сильный • опытный игрок</small></button></div><label>Ставка — максимум ${max.toLocaleString('ru-RU')} 🪙</label><input id="botStake" type="number" min="0" max="${max}" step="1" value="0" placeholder="Любая сумма"><div class="quick-stakes">${[0,1000,5000,10000,25000,50000,100000].filter(x=>x<=max).map(x=>`<button type="button" data-stake="${x}">${x.toLocaleString('ru-RU')}</button>`).join('')}</div><button class="primary" id="startBot">Начать игру</button></div>`);let key='kettle';$$('[data-bot]').forEach(b=>b.onclick=()=>{$$('[data-bot]').forEach(x=>x.classList.remove('active'));b.classList.add('active');key=b.dataset.bot});$$('[data-stake]').forEach(b=>b.onclick=()=>$('#botStake').value=b.dataset.stake);$('#startBot').onclick=async()=>{try{const stake=stakeValue('#botStake');if(stake>me.chips)return alert('Ставка превышает ваш баланс');const j=await api('/api/bot/create',{method:'POST',body:JSON.stringify({uid:accountId,botKey:key,stake})});me=j.user;bot={uid:j.uid,roomId:j.room.id,room:j.room,botKey:key,stake:j.room.stake};mode='computer';lastResultKey=null;closeModal();showGame();syncBotData(j.room)}catch(e){alert(e.message)}}}
function onlineSetup(){const max=me.chips;openModal(`<div class="setup"><h2>🌐 Онлайн-игра</h2><p>Создайте новый стол или подключитесь к существующему.</p><label>Ставка — максимум ${max.toLocaleString('ru-RU')} 🪙</label><input id="onlineStake" type="number" min="0" max="${max}" step="1" value="0" placeholder="Любая сумма"><div class="quick-stakes">${[0,1000,5000,10000,25000,50000,100000].filter(x=>x<=max).map(x=>`<button type="button" data-online-stake="${x}">${x.toLocaleString('ru-RU')}</button>`).join('')}</div><button class="primary" id="createTable">Создать стол</button><div class="room-divider">ИЛИ</div><input id="joinCode" inputmode="numeric" maxlength="4" placeholder="Код стола (4 цифры)"><button class="primary" id="joinTable">Подключиться</button></div>`);$$('[data-online-stake]').forEach(b=>b.onclick=()=>$('#onlineStake').value=b.dataset.onlineStake);$('#createTable').onclick=createOnlineTable;$('#joinTable').onclick=joinOnlineTable;$('#joinCode').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4)}
async function createOnlineTable(){try{const j=await api('/api/room/create',{method:'POST',body:JSON.stringify({uid:accountId,stake:stakeValue('#onlineStake')})});me=j.user;online={uid:j.uid,roomId:j.room.id,side:'w',room:j.room};mode='online';closeModal();showGame();syncOnlineData(j.room)}catch(e){alert(e.message)}}
async function joinOnlineTable(){const code=$('#joinCode').value.trim();if(!/^\d{4}$/.test(code))return alert('Введите ровно 4 цифры кода стола');try{const j=await api('/api/room/join',{method:'POST',body:JSON.stringify({uid:accountId,roomId:code})});me=j.user;online={uid:j.uid,roomId:j.room.id,side:'b',room:j.room};mode='online';closeModal();showGame();syncOnlineData(j.room)}catch(e){alert(e.message)}}
function showGame(){state=parseFen(START);selected=null;pendingPromotion=null;lastResultKey=null;drawPromptKey=null;clearRematchTimer();$('#home').hidden=true;$('#game').hidden=false;$('#onlineBar').hidden=mode!=='online';$('#gameMode').textContent=mode==='computer'?'ИГРА С КОМПЬЮТЕРОМ':mode==='online'?'ОНЛАЙН-ИГРА':'ДВА ИГРОКА';$('#gameSub').textContent=mode==='computer'?(bot.room?.status==='finished'?'Завершена':`🤖 ${bot.botKey==='kettle'?'Чайник':bot.botKey==='maestro'?'Маэстро':'Шпилер'} • 🪙 ${bot.stake.toLocaleString('ru-RU')}`):mode==='online'?`Стол ${online.roomId} • 🪙 ${online.room?.stake?.toLocaleString('ru-RU')||0}`:'На одном устройстве';render();}
function syncBotData(room){bot.room=room;state=parseFen(room.fen);online.room=null;$('#whiteName').textContent=me.name;$('#blackName').textContent=room.botKey==='kettle'?'Чайник':room.botKey==='maestro'?'Маэстро':'Шпилер';$('#onlineBar').hidden=true;render();if(room.result)showResult(room.result,room.drawReason,room)}
function syncOnlineData(room){online.room=room;state=parseFen(room.fen);$('#whiteName').textContent=room.players.find(p=>p.side==='w')?.name||'Белые';$('#blackName').textContent=room.players.find(p=>p.side==='b')?.name||'Ожидание игрока';$('#roomLabel').textContent=`Стол ${room.id} • Ставка ${Number(room.stake).toLocaleString('ru-RU')}`;$('#onlineState').textContent=room.status==='waiting'?`Код: ${room.id} • ждём второго игрока`:room.result?`Завершено • банк ${Number(room.bank).toLocaleString('ru-RU')}`:`Банк: ${Number(room.bank).toLocaleString('ru-RU')} • ${room.turn===online.side?'Ваш ход':'Ход соперника'}`;$('#chatLog').innerHTML=(room.chat||[]).map(x=>`<div><b>${escapeHtml(x.name)}:</b> ${escapeHtml(x.text)}</div>`).join('');render();if(room.result)showResult(room.result,room.drawReason,room);if(room.drawOffer&&room.drawOffer!==online.side&&room.status==='playing'){const dkey=`${room.id}:${room.drawOffer}`;if(drawPromptKey!==dkey){drawPromptKey=dkey;openDrawResponse()}}}
function openDrawResponse(){openModal(`<div class="setup"><h2>🤝 Предложение ничьей</h2><p>Соперник предлагает завершить партию вничью.</p><div class="rematch-actions"><button class="primary" id="acceptDraw">Принять ничью</button><button class="ghost" id="declineDraw">Продолжить игру</button></div></div>`);$('#acceptDraw').onclick=()=>respondDraw(true);$('#declineDraw').onclick=()=>respondDraw(false)}
async function respondDraw(accept){try{const j=await api('/api/room/draw-response',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid,accept})});drawPromptKey=null;closeModal();syncOnlineData(j.room)}catch(e){alert(e.message)}}
function render(){if(!state)return;const b=$('#board');b.innerHTML='';b.className=`board board-${me?.inventory?.selectedBoard||'classic'}`;const moves=legal(state),targets=new Set(selected==null?[]:moves.filter(m=>m.from===selected).map(m=>m.to));for(let visual=0;visual<64;visual++){const sq=flipped?63-visual:visual,el=document.createElement('button');el.className=`square ${(file(sq)+rank(sq))%2?'dark':'light'} ${sq===selected?'selected':''} ${targets.has(sq)?(state.board[sq]?'capture':'legal'):''}`;el.dataset.s=sq;const pc=state.board[sq];if(pc){const sp=document.createElement('span');sp.className=`piece piece-${me?.inventory?.selectedPieces||'classic'} ${color(pc)==='w'?'white-piece':'black-piece'}`;sp.textContent=glyph[pc];el.appendChild(sp)}if(file(sq)===0||rank(sq)===0){const c=document.createElement('span');c.className='coord';c.textContent=rank(sq)===0?'abcdefgh'[file(sq)]:rank(sq)+1;el.appendChild(c)}el.onclick=()=>clickSquare(sq);b.appendChild(el)}$('#message').textContent=statusText();const clocks=mode==='online'?online.room?.clocks:mode==='computer'?bot.room?.clocks:null;$('#whiteClock').textContent=clocks?fmt(clocks.w):'—';$('#blackClock').textContent=clocks?fmt(clocks.b):'—';$('#moves').innerHTML='';if(mode==='online'&&online.room?.lastMove)$('#moves').textContent=`${online.room.lastMove.from} → ${online.room.lastMove.to}`;if(mode==='computer'&&bot.room?.lastMove)$('#moves').textContent=`${bot.room.lastMove.from} → ${bot.room.lastMove.to}`}
function statusText(){const ms=legal(state);if(ms.length===0)return check(state,state.side)?(state.side==='w'?'МАТ — победа чёрных':'МАТ — победа белых'):'ПАТ — ничья';if(state.half>=150)return'Ничья — 75 ходов';return state.side==='w'?'Ход белых':'Ход чёрных'}
function clickSquare(s){const mySide=mode==='online'?online.side:mode==='computer'?'w':state.side;if(state.side!==mySide||pendingPromotion)return;if(selected==null){if(state.board[s]&&color(state.board[s])===state.side)selected=s;render();return}const m=legal(state).find(x=>x.from===selected&&x.to===s);if(m){if(m.promotion){pendingPromotion=m;showPromotion();return}commit(m)}else if(state.board[s]&&color(state.board[s])===state.side)selected=s;else selected=null;render()}
async function commit(m){if(mode==='online'){try{const j=await api('/api/room/move',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid,from:m.from,to:m.to,promotion:m.promotion||null})});me=j.user;syncOnlineData(j.room)}catch(e){alert(e.message)}}else if(mode==='computer'){try{const j=await api('/api/bot/move',{method:'POST',body:JSON.stringify({roomId:bot.roomId,uid:bot.uid,from:m.from,to:m.to,promotion:m.promotion||null})});me=j.user;syncBotData(j.room)}catch(e){alert(e.message)}}else{state=apply(state,m);selected=null;render()}}
function showPromotion(){const wrap=$('#promotion');wrap.hidden=false;$('#promoButtons').innerHTML='';for(const q of['Q','R','B','N']){const x=document.createElement('button');x.className='promo';x.textContent=glyph[q];x.onclick=()=>{pendingPromotion.promotion=q;wrap.hidden=true;const m=pendingPromotion;pendingPromotion=null;commit(m)};$('#promoButtons').appendChild(x)}}
function clearRematchTimer(){if(rematchTimer){clearInterval(rematchTimer);rematchTimer=null}}
function showResult(result,reason,room){const key=`${mode}:${room?.id||''}:${result}:${reason||''}`;let text=result==='1-0'?'Победа белых':result==='0-1'?'Победа чёрных':'Ничья';if(reason)text+=` • ${reason}`;$('#message').textContent=text;if(lastResultKey===key)return;lastResultKey=key;clearRematchTimer();if(mode==='local')return;const deadline=room?.rematch?.deadline||Date.now()+10000;let asked=!!room?.rematch?.requested;openModal(`<div class="setup rematch-box"><h2>🏆 Партия завершена</h2><p>${escapeHtml(text)}</p><p>Хотите сыграть реванш? Время выбора: <b id="rematchSeconds">10</b> сек.</p><div class="rematch-actions"><button class="primary" id="rematchYes">🔄 Реванш</button><button class="ghost" id="rematchNo">Нет</button></div><div id="rematchState">${asked?'Вы выбрали реванш. Ждём соперника…':'Выберите действие.'}</div></div>`);const tick=()=>{const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));const el=$('#rematchSeconds');if(el)el.textContent=left;if(left<=0){clearRematchTimer();const st=$('#rematchState');if(st)st.textContent='Время вышло — реванш закрыт.';const y=$('#rematchYes');if(y)y.disabled=true}};tick();rematchTimer=setInterval(tick,200);$('#rematchYes').onclick=async()=>{try{const url=mode==='online'?'/api/room/rematch':'/api/bot/rematch',payload=mode==='online'?{roomId:online.roomId,uid:online.uid,accept:true}:{roomId:bot.roomId,uid:bot.uid,accept:true};const j=await api(url,{method:'POST',body:JSON.stringify(payload)});me=j.user;lastResultKey=null;closeModal();if(mode==='online')syncOnlineData(j.room);else syncBotData(j.room)}catch(e){alert(e.message)}};$('#rematchNo').onclick=async()=>{if(mode==='online'){try{await api('/api/room/rematch',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid,accept:false})})}catch(e){} } clearRematchTimer();closeModal()}}

async function syncBot(){if(!bot.uid||$('#game').hidden)return;try{const j=await api(`/api/bot/sync?roomId=${encodeURIComponent(bot.roomId)}&uid=${encodeURIComponent(bot.uid)}`);me=j.user;syncBotData(j.room)}catch(e){if(!String(e.message).includes('Сессия'))console.warn(e)}}
async function syncOnline(){if(!online.uid||$('#game').hidden)return;try{const j=await api(`/api/room/sync?roomId=${encodeURIComponent(online.roomId)}&uid=${encodeURIComponent(online.uid)}`);me=j.user;syncOnlineData(j.room)}catch(e){if(!String(e.message).includes('Стол'))console.warn(e)}}
async function resignGame(){if(mode==='local')return alert('В локальной партии сдача не нужна.');if(!confirm('Сдаться и завершить игру?'))return;try{const url=mode==='online'?'/api/room/resign':'/api/bot/resign',payload=mode==='online'?{roomId:online.roomId,uid:online.uid}:{roomId:bot.roomId,uid:bot.uid};const j=await api(url,{method:'POST',body:JSON.stringify(payload)});me=j.user;if(mode==='online')syncOnlineData(j.room);else syncBotData(j.room)}catch(e){alert(e.message)}}
async function offerDraw(){if(mode!=='online')return alert('Предложение ничьей доступно только онлайн.');try{drawPromptKey=null;const j=await api('/api/room/draw-offer',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid})});syncOnlineData(j.room)}catch(e){alert(e.message)}}
async function sendChat(){if(mode!=='online'||!online.uid)return;const i=$('#chatInput');if(!i.value.trim())return;try{const j=await api('/api/room/chat',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid,text:i.value})});i.value='';syncOnlineData(j.room)}catch(e){alert(e.message)}}
function openShop(){if(!me||!store)return;const boards=store.boards,pieces=store.pieces,ownedB=new Set(me.inventory.boards),ownedP=new Set(me.inventory.pieces);const card=(x,type,owned,selected)=>`<div class="shop-item ${selected?'active':''}"><div class="shop-preview ${type}-${x[0]}">${type==='board'?'▦':'♔'}</div><b>${x[1]}</b><small>${x[2]}</small><span>🪙 ${x[3]===0?'Бесплатно':Number(x[3]).toLocaleString('ru-RU')}</span><button data-buy-type="${type}" data-buy-id="${x[0]}" ${owned?'disabled':''}>${owned?(selected?'Выбрано':'Куплено'):(x[3]===0?'Получить':'Купить')}</button>${owned&&!selected?`<button class="ghost" data-select-type="${type}" data-select-id="${x[0]}">Выбрать</button>`:''}</div>`;openModal(`<div class="shop"><div class="shop-head"><div><h2>🛍 Магазин</h2><p>После покупки новый стиль автоматически становится активным.</p></div><div class="big-chips">🪙 ${Number(me.chips).toLocaleString('ru-RU')}</div></div><h3>5 видов досок</h3><div class="shop-grid">${boards.map(x=>card(x,'board',ownedB.has(x[0]),me.inventory.selectedBoard===x[0])).join('')}</div><h3>5 наборов фигур</h3><div class="shop-grid">${pieces.map(x=>card(x,'pieces',ownedP.has(x[0]),me.inventory.selectedPieces===x[0])).join('')}</div></div>`);$$('[data-buy-type]').forEach(b=>b.onclick=()=>shopBuy(b.dataset.buyType,b.dataset.buyId));$$('[data-select-type]').forEach(b=>b.onclick=()=>shopSelect(b.dataset.selectType,b.dataset.selectId))}
async function shopBuy(type,id){try{const j=await api('/api/shop/buy',{method:'POST',body:JSON.stringify({uid:accountId,type,itemId:id})});me=j.user;openShop();render();refreshHome()}catch(e){alert(e.message)}}
async function shopSelect(type,id){try{const j=await api('/api/shop/select',{method:'POST',body:JSON.stringify({uid:accountId,type,itemId:id})});me=j.user;openShop();render();refreshHome()}catch(e){alert(e.message)}}
async function openLeaderboard(){try{const j=await api('/api/leaderboard?by=chips');openModal(`<div class="leaderboard"><h2>🏆 Лидерство</h2><div class="leader-tabs"><button id="lbChips" class="primary">По фишкам</button><button id="lbRank" class="ghost">По рангам</button></div><div id="lbList">${leaderRows(j.players)}</div><div class="rank-table"><b>Система рангов</b>${j.ranks.map(r=>`<div>Ур. ${r.level} • ${r.name} — от ${r.wins} побед</div>`).join('')}</div></div>`);$('#lbChips').onclick=()=>loadLeaderboard('chips');$('#lbRank').onclick=()=>loadLeaderboard('rank')}catch(e){alert(e.message)}}
async function loadLeaderboard(by){try{const j=await api('/api/leaderboard?by='+by);$('#lbList').innerHTML=leaderRows(j.players);$('#lbChips').className=by==='chips'?'primary':'ghost';$('#lbRank').className=by==='rank'?'primary':'ghost'}catch(e){alert(e.message)}}
function leaderRows(list){return list.length?list.map(u=>`<div class="leader-row"><b>#${u.position} ${escapeHtml(u.name)}</b><span>${u.rank.name} • ${u.wins} побед • 🪙 ${Number(u.chips).toLocaleString('ru-RU')}</span></div>`).join(''):'<p>Пока нет игроков.</p>'}
function openAdmin(){const pass=prompt('Пароль администратора');if(pass===null)return;api('/api/admin/login',{method:'POST',body:JSON.stringify({password:pass})}).then(()=>renderAdmin(pass)).catch(()=>alert('Неверный пароль'))}
async function renderAdmin(pass){try{const j=await api('/api/admin/players?password='+encodeURIComponent(pass));openModal(`<div class="admin"><h2>🛡 Админ-панель</h2><div class="admin-danger"><button id="clearDB">🗑 Полностью очистить базу</button></div><div class="admin-list">${j.players.length?j.players.map(u=>`<div class="admin-user"><div><b>${escapeHtml(u.name)}</b><small>${u.rank.name} • ${u.wins} побед<br>🪙 ${Number(u.chips).toLocaleString('ru-RU')} ${u.vip?'• VIP':''} ${u.banned?'• БАН':''}</small></div><div class="admin-actions"><button data-admin="chips" data-id="${u.id}">+Фишки</button><button data-admin="vip" data-id="${u.id}">${u.vip?'VIP OFF':'VIP'}</button><button data-admin="ban" data-id="${u.id}">${u.banned?'Разбан':'Бан'}</button></div></div>`).join(''):'<p>Игроков пока нет.</p>'}</div></div>`);$('#clearDB').onclick=async()=>{if(!confirm('Удалить ВСЕ аккаунты и комнаты?'))return;try{await api('/api/admin/action',{method:'POST',body:JSON.stringify({password:pass,action:'clear_database'})});location.reload()}catch(e){alert(e.message)}};$$('[data-admin]').forEach(b=>b.onclick=async()=>{try{const action=b.dataset.admin,id=b.dataset.id,body={password:pass,action,userId:id};if(action==='chips'){const amount=Number(prompt('Сколько фишек начислить?','100000'));if(!Number.isFinite(amount))return;body.amount=amount}else if(action==='vip')body.value=b.textContent==='VIP OFF'?false:true;else body.value=b.textContent==='Бан';await api('/api/admin/action',{method:'POST',body:JSON.stringify(body)});renderAdmin(pass)}catch(e){alert(e.message)}})}catch(e){alert(e.message)}}
const RULES_HTML=`<div class="rules-content"><h2>📖 Правила SANI CHESS</h2><p class="lead">Полные классические правила: легальные ходы, шах, мат, пат, рокировка, en passant, превращение пешки, повторения и контроль 75 ходов.</p><h3>Цель</h3><p>Поставить мат королю соперника. Короля нельзя оставлять под шахом.</p><h3>Фигуры</h3><p>Король ходит на одно поле, ферзь — по линиям и диагоналям, ладья — по линиям, слон — по диагоналям, конь — буквой Г и может перепрыгивать фигуры.</p><h3>Пешка</h3><p>Движется вперёд, со стартовой позиции может сделать два поля, бьёт по диагонали. En passant разрешён только непосредственно после двойного хода пешки соперника. На последней горизонтали пешка превращается в ферзя, ладью, слона или коня.</p><h3>Рокировка</h3><p>Король и ладья не должны ранее двигаться; поля между ними должны быть свободны; король не может быть под шахом, проходить через атакованное поле или оказаться под шахом.</p><h3>Ничья</h3><p>Пат и мёртвая позиция дают ничью. 50 ходов — право требовать ничью, 75 ходов — автоматическая ничья по правилам, если мат не поставлен последним ходом. Троекратное повторение может быть заявлено, пятикратное повторение — автоматическая ничья.</p><h3>Ставки</h3><p>В партиях за фишки ставка удерживается до результата. Победитель получает банк, при ничьей ставка возвращается.</p></div>`;
const ABOUT_HTML=`<div class="about-content"><h2>🏢 О разработчиках</h2><div class="about-brand"><div class="about-logo">♔</div><div><h3>SANI GROUP</h3><p>SANI CHESS</p></div></div><p><b>Разработчик и владелец:</b> SANI GROUP</p><p>Игровой движок, компьютерный соперник, онлайн 1×1, магазин, рейтинги и адаптивный интерфейс для ПК и телефона.</p></div>`;
function startGame(which){if(which==='computer')return botSetup();if(which==='online')return onlineSetup();mode='local';state=parseFen(START);online={uid:null,roomId:null,side:null,room:null};bot={uid:null,roomId:null,room:null,botKey:null,stake:0};showGame()}
async function leaveCurrent(){if(mode==='online'&&online.uid)fetch('/api/room/leave',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:online.roomId,uid:online.uid})}).catch(()=>{});if(mode==='computer'&&bot.uid)fetch('/api/bot/leave',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roomId:bot.roomId,uid:bot.uid})}).catch(()=>{})}
$$('[data-action]').forEach(b=>{if(b.id==='shopHome')return;b.onclick=e=>{e.preventDefault();const a=b.dataset.action;if(a==='rules')openModal(RULES_HTML);else if(a==='about')openModal(ABOUT_HTML);else if(a==='computer')startGame('computer');else if(a==='local')startGame('local');else if(a==='online')startGame('online')}});
$('#back').onclick=async()=>{clearRematchTimer();await leaveCurrent();$('#game').hidden=true;$('#home').hidden=false;if(gameTimer){clearInterval(gameTimer);gameTimer=null}online={uid:null,roomId:null,side:null,room:null};bot={uid:null,roomId:null,room:null,botKey:null,stake:0};authenticate()};
$('#newGame').onclick=()=>startGame(mode);$('#flip').onclick=()=>{flipped=!flipped;render()};$('#closeModal').onclick=closeModal;$('#resign').onclick=resignGame;$('#drawOffer').onclick=offerDraw;$('#sendChat').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()};
setInterval(()=>{if(mode==='online'&&!$('#game').hidden)syncOnline();if(mode==='computer'&&!$('#game').hidden)syncBot()},2000);setInterval(()=>{if(!$('#game').hidden&&state)render()},1000);document.addEventListener('DOMContentLoaded',authActions);
