const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let state=null, mode='computer', flipped=false, selected=null, pendingPromotion=null, gameTimer=null, hintBusy=false, hintMove=null, botGameId=null, botStake=0, botLevel=2, botSettled=false, online={uid:null,roomId:null,side:null}, accountId=localStorage.getItem('saniChessAccount')||null, me=null, store=null;
const START='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const glyph={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
function parseFen(fen){const [pl,side,castling,ep,half,full]=fen.split(/\s+/),b=Array(64).fill(null);let r=7,f=0;for(const c of pl){if(c==='/'){r--;f=0}else if(/[1-8]/.test(c))f+=+c;else b[r*8+f++]=c}return{board:b,side,castling:castling==='-'?'':castling,ep:ep==='-'?null:(ep.charCodeAt(0)-97)+8*(+ep[1]-1),half:+half,full:+full}}
function file(s){return s%8}function rank(s){return Math.floor(s/8)}function color(p){return p===p?.toUpperCase()?'w':'b'}function enemy(c){return c==='w'?'b':'w'}
const KN=[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]],KI=[[1,1],[1,0],[1,-1],[0,1],[0,-1],[-1,1],[-1,0],[-1,-1]];
function attacked(st,s,by){const f=file(s),r=rank(s),pr=r+(by==='w'?-1:1),pc=by==='w'?'P':'p';if(pr>=0&&pr<8)for(const df of[-1,1])if(f+df>=0&&f+df<8&&st.board[pr*8+f+df]===pc)return true;const nk=by==='w'?'N':'n';for(const[dF,dR]of KN){let F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[R*8+F]===nk)return true}const kk=by==='w'?'K':'k';for(const[dF,dR]of KI){let F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[R*8+F]===kk)return true}for(const[dF,dR]of[[1,0],[-1,0],[0,1],[0,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[R*8+F];if(p){if(color(p)===by&&'rq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}for(const[dF,dR]of[[1,1],[1,-1],[-1,1],[-1,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[R*8+F];if(p){if(color(p)===by&&'bq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}return false}
function king(st,c){return st.board.findIndex(p=>p===(c==='w'?'K':'k'))}function check(st,c){return king(st,c)<0||attacked(st,king(st,c),enemy(c))}
function clone(s){return{board:s.board.slice(),side:s.side,castling:s.castling,ep:s.ep,half:s.half,full:s.full}}
function pseudo(st){const c=st.side,m=[];const add=(f,t,x={})=>m.push({from:f,to:t,...x});for(let from=0;from<64;from++){const p=st.board[from];if(!p||color(p)!==c)continue;const f=file(from),r=rank(from),u=p.toUpperCase();if(u==='P'){const d=c==='w'?1:-1, sr=c==='w'?1:6, pr=c==='w'?7:0, rr=r+d;if(rr>=0&&rr<8){const one=rr*8+f;if(!st.board[one]){if(rr===pr)['Q','R','B','N'].forEach(q=>add(from,one,{promotion:c==='w'?q:q.toLowerCase()}));else add(from,one);if(r===sr){const two=(r+2*d)*8+f;if(!st.board[two])add(from,two)}}for(const df of[-1,1]){const F=f+df;if(F<0||F>7)continue;const to=rr*8+F,t=st.board[to];if(t&&color(t)!==c){if(rr===pr)['Q','R','B','N'].forEach(q=>add(from,to,{promotion:c==='w'?q:q.toLowerCase()}));else add(from,to)}if(st.ep===to)add(from,to,{ep:true})}}}else if(u==='N'){for(const[dF,dR]of KN){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=R*8+F,t=st.board[to];if(!t||color(t)!==c)add(from,to)}}}else if(u==='K'){for(const[dF,dR]of KI){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=R*8+F,t=st.board[to];if(!t||color(t)!==c)add(from,to)}}const rr=c==='w'?0:7;if(from===rr*8+4&&!check(st,c)){const K=c==='w'?'K':'k',Q=c==='w'?'Q':'q';if(st.castling.includes(K)&&st.board[rr*8+7]===(c==='w'?'R':'r')&&!st.board[rr*8+5]&&!st.board[rr*8+6]&&!attacked(st,rr*8+5,enemy(c))&&!attacked(st,rr*8+6,enemy(c)))add(from,rr*8+6,{castle:'K'});if(st.castling.includes(Q)&&st.board[rr*8]===(c==='w'?'R':'r')&&!st.board[rr*8+1]&&!st.board[rr*8+2]&&!st.board[rr*8+3]&&!attacked(st,rr*8+3,enemy(c))&&!attacked(st,rr*8+2,enemy(c)))add(from,rr*8+2,{castle:'Q'})}}else{const ds=u==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:u==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const[dF,dR]of ds){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const to=R*8+F,t=st.board[to];if(!t)add(from,to);else{if(color(t)!==c)add(from,to);break}F+=dF;R+=dR}}}}return m}
function apply(st,m){const n=clone(st),p=n.board[m.from],c=n.side,u=p.toUpperCase(),target=n.board[m.to];n.board[m.from]=null;if(m.ep)n.board[m.to+(c==='w'?-8:8)]=null;n.board[m.to]=m.promotion||p;if(m.castle){const rr=c==='w'?0:7;if(m.castle==='K'){n.board[rr*8+5]=n.board[rr*8+7];n.board[rr*8+7]=null}else{n.board[rr*8+3]=n.board[rr*8];n.board[rr*8]=null}}if(u==='K')n.castling=n.castling.replace(c==='w'?/[KQ]/g:/[kq]/g,'');if(u==='R'){if(m.from===0)n.castling=n.castling.replace('Q','');if(m.from===7)n.castling=n.castling.replace('K','');if(m.from===56)n.castling=n.castling.replace('q','');if(m.from===63)n.castling=n.castling.replace('k','')}if(target?.toUpperCase()==='R'){if(m.to===0)n.castling=n.castling.replace('Q','');if(m.to===7)n.castling=n.castling.replace('K','');if(m.to===56)n.castling=n.castling.replace('q','');if(m.to===63)n.castling=n.castling.replace('k','')}n.ep=null;if(u==='P'&&Math.abs(m.to-m.from)===16)n.ep=(m.from+m.to)/2;n.half=(u==='P'||target||m.ep)?0:n.half+1;if(c==='b')n.full++;n.side=enemy(c);return n}
function legal(st){return pseudo(st).filter(m=>!check(apply(st,m),st.side))}
function notation(m,st){const p=st.board[m.from].toUpperCase();if(m.castle)return m.castle==='K'?'O-O':'O-O-O';const files='abcdefgh';return `${p==='P'?'':p}${files[file(m.from)]}${rank(m.from)+1}${m.promotion?'='+m.promotion.toUpperCase():''}→${files[file(m.to)]}${rank(m.to)+1}`}
function render(){if(!state)return;const b=$('#board');b.innerHTML='';b.className=`board board-${me?.inventory?.selectedBoard||'classic'}`;const moves=legal(state);const targets=new Set(selected==null?[]:moves.filter(m=>m.from===selected).map(m=>m.to));for(let visual=0;visual<64;visual++){const s=flipped?63-visual:visual,el=document.createElement('button');el.className=`square ${(file(s)+rank(s))%2?'dark':'light'} ${s===selected?'selected':''} ${targets.has(s)?(state.board[s]?'capture':'legal'):''} ${hintMove&&(s===hintMove.from||s===hintMove.to)?'hint-square':''}`;el.dataset.s=s;const p=state.board[s];if(p){const sp=document.createElement('span');sp.className=`piece piece-${me?.inventory?.selectedPieces||'classic'} ${color(p)==='w'?'white-piece':'black-piece'}`;sp.textContent=glyph[p];el.appendChild(sp)}if(file(s)===0||rank(s)===0){const c=document.createElement('span');c.className='coord';c.textContent=rank(s)===0?'abcdefgh'[file(s)]:rank(s)+1;el.appendChild(c)}el.onclick=()=>clickSquare(s);b.appendChild(el)}$('#message').textContent=statusText()+(me?.vip&&!gameOver()?' • 👑 VIP-подсказка доступна':'');const hb=$('#hintBtn');if(hb){hb.hidden=!me?.vip||!state||gameOver();hb.textContent=hintBusy?'⏳ Анализ…':'💡 Подсказка';}$('#whiteClock').textContent=mode==='online'?fmt(online.room?.clocks?.w??600000):'10:00';$('#blackClock').textContent=mode==='online'?fmt(online.room?.clocks?.b??600000):'10:00';}
function statusText(){const ms=legal(state);if(ms.length===0)return check(state,state.side)?(state.side==='w'?'МАТ — победа чёрных':'МАТ — победа белых'):'ПАТ — ничья';if(state.half>=150)return'Ничья — 75 ходов';return state.side==='w'?'Ход белых':'Ход чёрных'}
function fmt(ms){ms=Math.max(0,ms);return`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`}
function clickSquare(s){if(mode==='online'&&state.side!==online.side)return;if(pendingPromotion)return;if(selected==null){if(state.board[s]&&color(state.board[s])===state.side)selected=s}else{const m=legal(state).find(x=>x.from===selected&&x.to===s);if(m){if(m.promotion){pendingPromotion=m;showPromotion()}else commit(m)}else if(state.board[s]&&color(state.board[s])===state.side)selected=s;else selected=null}render()}
function commit(m){const old=state;const text=notation(m,old);state=apply(state,m);hintMove=null;selected=null;addMove(text);render();settleBotIfNeeded();if(mode==='computer'&&state.side==='b'&&!gameOver()){setTimeout(aiMove,180)}if(mode==='online')sendMove(m)}
async function requestHint(){if(!me?.vip||!state||gameOver()||hintBusy)return;hintBusy=true;hintMove=null;render();try{const j=await api('/api/hint',{method:'POST',body:JSON.stringify({uid:accountId,fen:toFen(state)})});if(j.available){hintMove={from:j.from,to:j.to};render();openModal(`<div class="hint-modal"><h2>👑 Подсказка гроссмейстера</h2><p><b>Рекомендуемый ход:</b> ${escapeHtml(j.move.from)} → ${escapeHtml(j.move.to)}${j.move.promotion?' = '+escapeHtml(j.move.promotion):''}</p><div class="hint-block"><b>📖 Почему:</b><p>${escapeHtml(j.reason)}</p></div><div class="hint-block"><b>⚔️ Тактическая угроза:</b><p>${escapeHtml(j.threat)}</p></div><div class="hint-block"><b>♟️ Что угрожает соперник:</b><p>${escapeHtml(j.threat)}</p></div><div class="hint-block"><b>💀 Матовая атака:</b><p>${escapeHtml(j.mateAttack)}</p></div><button class="primary" id="closeHint">Понятно</button></div>`);$('#closeHint').onclick=closeModal}else openModal('<div class="hint-modal"><h2>👑 Подсказка</h2><p>В текущей позиции нет доступного хода — партия завершена.</p></div>')}catch(e){openModal(`<div class="hint-modal"><h2>👑 Подсказка</h2><p>${escapeHtml(e.message)}</p></div>`)}finally{hintBusy=false;render()}}
function toFen(st){let p='';for(let r=7;r>=0;r--){let empty=0;for(let f=0;f<8;f++){const x=st.board[r*8+f];if(!x)empty++;else{if(empty){p+=empty;empty=0}p+=x}}if(empty)p+=empty;if(r)p+='/'}return `${p} ${st.side} ${st.castling||'-'} ${st.ep==null?'-':String.fromCharCode(97+file(st.ep))+(Math.floor(st.ep/8)+1)} ${st.half} ${st.full}`}
function showPromotion(){const wrap=$('#promotion');wrap.hidden=false;$('#promoButtons').innerHTML='';for(const q of['Q','R','B','N']){const x=document.createElement('button');x.className='promo';x.textContent=glyph[q];x.onclick=()=>{pendingPromotion.promotion=q;wrap.hidden=true;const m=pendingPromotion;pendingPromotion=null;commit(m)};$('#promoButtons').appendChild(x)}}
function addMove(t){const d=document.createElement('div');d.textContent=t;$('#moves').appendChild(d);$('#moves').scrollTop=99999}
function gameOver(){return legal(state).length===0||state.half>=150}
async function settleBotIfNeeded(){if(mode!=='computer'||!botGameId||botSettled||!gameOver())return;botSettled=true;const ms=legal(state),isMate=ms.length===0&&check(state,state.side);let result='draw';if(isMate)result=state.side==='w'?'loss':'win';else if(state.half>=150)result='draw';try{const j=await api('/api/bot/settle',{method:'POST',body:JSON.stringify({uid:accountId,gameId:botGameId,result})});me=j.user;refreshHome();}catch(e){botSettled=false}}

const val={P:100,N:320,B:330,R:500,Q:900,K:20000};
function evaluate(st){let score=0;for(const p of st.board)if(p)score+=(color(p)==='w'?1:-1)*val[p.toUpperCase()];return score+(legal(st).length*(st.side==='w'?2:-2))}
function aiMove(){if(gameOver()||state.side!=='b')return;let best=-Infinity,bm=null;for(const m of legal(state)){const sc=-search(apply(state,m),botLevel===1?1:botLevel===2?2:3,-Infinity,Infinity);if(sc>best){best=sc;bm=m}}if(bm)commit(bm)}
function search(st,d,a,b){if(d===0)return stateSide(st)==='w'?evaluate(st):-evaluate(st);const ms=legal(st);if(!ms.length){if(check(st,st.side))return -20000-d*10;return 0}let best=-Infinity;for(const m of ms){const sc=-search(apply(st,m),d-1,-b,-a);if(sc>best)best=sc;if(sc>a)a=sc;if(a>=b)break}return best}function stateSide(st){return st.side}
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const j=await r.json();if(!j.ok)throw new Error(j.error||'Ошибка');return j}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').hidden=false}function closeModal(){$('#modal').hidden=true}
function startGame(m){mode=m;$('#home').hidden=true;$('#game').hidden=false;$('#onlineBar').hidden=m!=='online';state=parseFen(START);selected=null;$('#moves').innerHTML='';$('#gameMode').textContent=m==='computer'?'ПРОТИВ КОМПЬЮТЕРА':m==='online'?'ОНЛАЙН':'ДВА ИГРОКА';$('#gameSub').textContent=m==='computer'?`SANI AI • ${botLevel===1?'Чайник':botLevel===2?'Шпилер':'Маэстро'} • ставка ${botStake}`:m==='online'?'Онлайн-стол':'На одном устройстве';$('#whiteName').textContent=m==='computer'?(me?.name||'Вы')+(me?.vip?' 👑 VIP':''):'Белые';$('#blackName').textContent=m==='computer'?'SANI AI':'Чёрные';render();if(m==='online')openOnline();}
function openOnline(){openModal(`<h2>🌐 Онлайн-игра</h2><p>Создайте новый стол или подключитесь к существующему.</p><div class="form"><input id="playerName" value="${escapeHtml(me?.name||'')}" maxlength="24" placeholder="Ваш никнейм"><div class="chip-balance">🪙 Фишки: <b>${me?.chips??0}</b></div><label>Ставка <select id="stake"><option value="0">Без ставки</option><option value="100">100</option><option value="250">250</option><option value="500">500</option></select></label><button class="primary" id="createRoom">Создать стол</button><input id="roomCode" maxlength="6" placeholder="Код стола"><button class="primary" id="joinRoom">Подключиться</button></div>`);$('#createRoom').onclick=()=>onlineCreate();$('#joinRoom').onclick=()=>onlineJoin();}
async function onlineCreate(){try{const j=await api('/api/room/create',{method:'POST',body:JSON.stringify({uid:accountId, name:$('#playerName').value, stake:Number($('#stake').value||0)})});online={uid:j.uid,roomId:j.room.id,side:j.self,room:j.room};closeModal();$('#roomLabel').textContent=`СТОЛ ${j.room.id}`;syncOnline();}catch(e){alert(e.message)}}
async function onlineJoin(){try{const j=await api('/api/room/join',{method:'POST',body:JSON.stringify({uid:accountId, name:$('#playerName').value,roomId:$('#roomCode').value})});online={uid:j.uid,roomId:j.room.id,side:j.self,room:j.room};closeModal();$('#roomLabel').textContent=`СТОЛ ${j.room.id}`;syncOnline();}catch(e){alert(e.message)}}
async function syncOnline(){if(!online.uid)return;try{const j=await api(`/api/room/sync?roomId=${online.roomId}&uid=${online.uid}`);online.room=j.room;online.side=j.self;state=parseFen(j.room.fen);$('#connection').textContent='● ОНЛАЙН';$('#onlineState').textContent=j.room.status==='waiting'?'Ожидание второго игрока…':j.room.result?`Игра завершена: ${j.room.result}`:'Игра идёт';const bp=j.room.players.find(p=>p.side==='b'),wp=j.room.players.find(p=>p.side==='w');$('#blackName').textContent=bp?.name||'Ожидание';$('#whiteName').textContent=wp?.name||'Ожидание';$('#chatLog').innerHTML=j.room.chat.map(x=>`<div><b>${escapeHtml(x.name)}:</b> ${escapeHtml(x.text)}</div>`).join('');render();}catch(e){$('#connection').textContent='● ОШИБКА'}}
async function sendMove(m){try{const j=await api('/api/room/move',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid,from:m.from,to:m.to,promotion:m.promotion||null})});online.room=j.room;state=parseFen(j.room.fen);render()}catch(e){alert(e.message);syncOnline()}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#back').onclick=()=>{$('#game').hidden=true;$('#home').hidden=false;if(gameTimer)clearInterval(gameTimer)};$('#newGame').onclick=()=>startGame(mode);$('#flip').onclick=()=>{flipped=!flipped;render()};$('#closeModal').onclick=closeModal;$('#resign').onclick=()=>{if(mode==='online')return alert('В этой версии серверная сдача будет добавлена следующим обновлением.');alert('Партия завершена.');};$('#drawOffer').onclick=()=>alert('Предложение ничьей отправлено.');$('#sendChat').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()};async function sendChat(){if(!online.uid)return;const i=$('#chatInput');if(!i.value.trim())return;try{await api('/api/room/chat',{method:'POST',body:JSON.stringify({roomId:online.roomId,uid:online.uid,text:i.value})});i.value='';syncOnline()}catch(e){alert(e.message)}}
const RULES_HTML = `<div class="rules-content">
<h2>📖 Полные правила SANI CHESS</h2>
<p class="lead">SANI CHESS использует классические правила шахмат. Цель игры — поставить мат королю соперника. Сервер онлайн-игры является источником истины и проверяет каждый ход.</p>
<h3>1. Цель игры</h3><p>Белые и чёрные по очереди делают ходы. Побеждает игрок, который поставил мат королю соперника. Игрок также может сдаться. Партия заканчивается вничью при предусмотренных правилами основаниях.</p>
<h3>2. Доска и начальная позиция</h3><p>Доска состоит из 64 полей: 8 вертикалей a–h и 8 горизонталей 1–8. В начальной позиции белые находятся на 1–2-й горизонталях, чёрные — на 7–8-й. Белые ходят первыми.</p>
<h3>3. Король</h3><p>Король ходит на одно поле в любом направлении. Король не может перейти на поле, атакуемое соперником. Короля нельзя «взять»: позиция с атакованным королём называется шахом, а игрок обязан немедленно устранить шах.</p>
<h3>4. Ферзь</h3><p>Ферзь ходит на любое количество свободных полей по вертикали, горизонтали или диагонали. Перепрыгивать через фигуры нельзя.</p>
<h3>5. Ладья</h3><p>Ладья ходит на любое количество свободных полей по вертикали или горизонтали. Через фигуры не перепрыгивает.</p>
<h3>6. Слон</h3><p>Слон ходит на любое количество свободных полей по диагонали. Он всегда остаётся на цвете поля, на котором начал движение.</p>
<h3>7. Конь</h3><p>Конь ходит буквой «Г»: на 2 поля по одной координате и на 1 поле по другой. Это единственная фигура, которая может перепрыгивать через другие фигуры.</p>
<h3>8. Пешка</h3><ul><li>Белая пешка движется к 8-й горизонтали, чёрная — к 1-й.</li><li>Обычный ход — на 1 поле вперёд, если оно свободно.</li><li>Из начальной позиции можно пойти на 2 поля, если оба поля свободны.</li><li>Взятие выполняется на 1 поле по диагонали вперёд.</li><li>Назад пешка не ходит.</li></ul>
<h3>9. Взятие на проходе (en passant)</h3><p>Если пешка из начальной позиции сделала двойной ход и оказалась рядом с пешкой соперника, соперник может на следующем полуходу взять её «на проходе», перейдя на поле, которое пешка перепрыгнула. Право действует только непосредственно следующим ходом; затем исчезает.</p>
<h3>10. Превращение пешки</h3><p>Достигнув последней горизонтали, пешка обязательно превращается в ферзя, ладью, слона или коня того же цвета. Можно выбрать любую из четырёх фигур; король и пешка недоступны для выбора.</p>
<h3>11. Рокировка</h3><p>Короткая рокировка: O-O — король e1–g1, ладья h1–f1 для белых; аналогично e8–g8 и h8–f8 для чёрных. Длинная: O-O-O — король e1–c1, ладья a1–d1; для чёрных e8–c8 и a8–d8.</p><ul><li>Право на рокировку должно сохраняться.</li><li>Король и соответствующая ладья должны находиться на исходных полях.</li><li>Между королём и ладьёй не должно быть фигур.</li><li>Король не должен находиться под шахом.</li><li>Поле, через которое проходит король, и поле назначения не должны быть атакованы.</li><li>При длинной рокировке поле b1/b8 может быть атаковано, поскольку король через него не проходит.</li></ul><p>После любого хода короля оба права рокировки этого цвета теряются. После хода исходной ладьи или её взятия теряется соответствующее право.</p>
<h3>12. Шах</h3><p>Король находится под шахом, если его поле атакует хотя бы одна фигура соперника. Нельзя сделать ход, после которого собственный король остаётся под шахом.</p>
<h3>13. Легальные ходы</h3><p>Сначала фигура должна соответствовать правилам движения, затем результат хода проверяется на безопасность собственного короля. Поэтому связанные фигуры не могут уйти, если после этого откроется шах королю.</p>
<h3>14. Мат</h3><p>Мат — король находится под шахом, и у игрока нет ни одного легального хода для устранения шаха. Мат означает немедленную победу соперника.</p>
<h3>15. Пат</h3><p>Пат — игрок не находится под шахом, но не имеет ни одного легального хода. Результат — ничья.</p>
<h3>16. Ничья по недостатку материала</h3><p>Партия может быть завершена ничьей, если никакая последовательность легальных ходов уже не может привести к мату. Типичные случаи: король против короля; король и слон против короля; король и конь против короля; король и слон против короля и слона, если слоны ходят по полям одного цвета. SANI CHESS не объявляет K+2N против K автоматически ничьёй только по составу фигур.</p>
<h3>17. Правило 50 ходов</h3><p>После 100 последовательных полуходов без хода пешки и без взятия возникает возможность заявить ничью по правилу 50 ходов.</p>
<h3>18. Правило 75 ходов</h3><p>После 150 последовательных полуходов без хода пешки и без взятия партия автоматически заканчивается ничьей, кроме случая, когда последний ход одновременно поставил мат.</p>
<h3>19. Повторение позиции</h3><p>Одинаковой считается позиция, в которой совпадают расположение фигур, сторона хода, права на рокировку и возможность взятия на проходе. Трёхкратное повторение даёт право заявить ничью; пятикратное повторение приводит к автоматической ничьей. Для определения повторений SANI CHESS использует хэш состояния позиции.</p>
<h3>20. Сдача и предложение ничьей</h3><p>Игрок может сдаться, после чего побеждает соперник. В онлайн-режиме игроки могут обмениваться предложением ничьей и принимать или отклонять его.</p>
<h3>21. Онлайн-игра</h3><p>В онлайн-партии сервер хранит актуальное состояние доски, очередь хода, специальные права и историю позиции. Клиент не может самостоятельно изменить результат или сделать нелегальный ход. При временном отключении соединения предусмотрено восстановление партии.</p>
<h3>22. Шахматные часы</h3><p>Если для режима задан контроль времени, часы идут только у игрока, чей ход. При истечении времени партия завершается согласно правилам выбранного контроля времени, если соперник имеет возможность поставить мат.</p>
<h3>23. Форматы позиции и ходы</h3><p>Внутреннее состояние включает доску 64 поля, сторону хода, четыре права рокировки, en passant target square, счётчик полуходов и номер полного хода. История позиций используется для определения повторений.</p>
</div>`;
const ABOUT_HTML = `<div class="about-content"><h2>🏢 О разработчиках</h2><div class="about-brand"><div class="about-logo">♔</div><div><h3>SANI GROUP</h3><p>SANI CHESS</p></div></div><p><b>Разработчик и владелец проекта:</b> SANI GROUP</p><p><b>Проект:</b> SANI CHESS — современная веб-игра в шахматы.</p><p><b>Направление разработки:</b> игровой движок, компьютерный соперник, онлайн-игра 1×1, адаптивный интерфейс для компьютеров и мобильных устройств.</p><p><b>Принцип проекта:</b> шахматные правила и проверка легальности ходов должны выполняться надёжно, а в онлайн-режиме критическая игровая логика находится на сервере.</p><div class="about-note">© ${new Date().getFullYear()} SANI GROUP. SANI CHESS.</div></div>`;

function openBotMenu(){openModal(`<div class="form"><h2>🤖 Игра с компьютером</h2><p>Выберите соперника и ставку. Ставка не может превышать ваш баланс.</p><label>Соперник<select id="botLevel"><option value="1">Чайник — самый лёгкий</option><option value="2" selected>Шпилер — нормальный</option><option value="3">Маэстро — сильный</option></select></label><label>Ставка <input id="botStake" type="number" min="0" max="${me.chips}" value="0"></label><button class="primary" id="startBot">Начать игру</button></div>`);$('#startBot').onclick=async()=>{const stake=Math.floor(Number($('#botStake').value)||0),level=Number($('#botLevel').value);if(stake<0||stake>me.chips)return openModal('<div class="hint-modal"><h2>Ставка</h2><p>Сумма ставки должна быть в пределах вашего баланса.</p></div>');try{const j=await api('/api/bot/start',{method:'POST',body:JSON.stringify({uid:accountId,stake,level})});me=j.user;botLevel=level;botStake=stake;botGameId=j.gameId;botSettled=false;closeModal();startGame('computer')}catch(e){openModal(`<div class="hint-modal"><h2>Не удалось начать игру</h2><p>${escapeHtml(e.message)}</p></div>`)}}}
function saveAccountId(id){accountId=id;localStorage.setItem('saniChessAccount',id)}
async function authenticate(){try{const j=await api('/api/auth',{method:'POST',body:JSON.stringify({id:accountId})});if(j.needsName){openModal(`<div class="auth-card"><div class="auth-logo">♔</div><h2>Добро пожаловать в SANI CHESS</h2><p>Введите никнейм. Он будет сохранён на сервере и останется за вами.</p><input id="firstNick" maxlength="24" placeholder="Ваш никнейм"><button class="primary" id="createAccount">Создать игрока</button></div>`);$('#createAccount').onclick=async()=>{const name=$('#firstNick').value.trim();if(!name)return alert('Введите никнейм');try{const x=await api('/api/auth',{method:'POST',body:JSON.stringify({id:accountId||'',name})});saveAccountId(x.user.id);me=x.user;store=x.store;closeModal();refreshHome()}catch(e){alert(e.message)}};return}me=j.user;store=j.store;saveAccountId(j.user.id);refreshHome()}catch(e){localStorage.removeItem('saniChessAccount');accountId=null;alert(e.message)}}
function refreshHome(){document.body.classList.add('authenticated');$('#connection').textContent=`● ${me.name}${me.vip?' 👑':''}`;$('#connection').title=`🪙 ${me.chips} фишек${me.vip?' • VIP':''}`;$$('[data-action]').forEach(b=>b.disabled=false);if(mode!=='online')render()}
function openShop(){const boards=store.boards,pieces=store.pieces,ownedB=new Set(me.inventory.boards),ownedP=new Set(me.inventory.pieces);const card=(x,type,owned,selected)=>{const vipOnly=x[4]==='vip',available=vipOnly?!!me.vip:owned;return `<div class="shop-item ${selected?'active':''} ${vipOnly?'vip-item':''}"><div class="shop-preview ${type}-${x[0]}">${type==='board'?'▦':'♔'}</div><b>${x[1]}</b><small>${x[2]}</small><span>${vipOnly?'👑 Только VIP':`🪙 ${x[3]===0?'Бесплатно':x[3]}`}</span>${vipOnly?`<button class="ghost" data-select-type="${type}" data-select-id="${x[0]}" ${!me.vip?'disabled':''}>${selected?'Выбрано':(me.vip?'Выбрать':'Нужен VIP')}</button>`:`<button data-buy-type="${type}" data-buy-id="${x[0]}" ${owned?'disabled':''}>${owned?(selected?'Выбрано':'Куплено'):(x[3]===0?'Получить':'Купить')}</button>${owned&&!selected?`<button class="ghost" data-select-type="${type}" data-select-id="${x[0]}">Выбрать</button>`:''}`}</div>`};openModal(`<div class="shop"><div class="shop-head"><div><h2>🛍 Магазин</h2><p>Доски и фигуры. VIP-предметы нельзя купить за фишки.</p></div><div class="big-chips">🪙 ${me.chips}</div></div><h3>Доски</h3><div class="shop-grid">${boards.map(x=>card(x,'board',ownedB.has(x[0]),me.inventory.selectedBoard===x[0])).join('')}</div><h3>Фигуры</h3><div class="shop-grid">${pieces.map(x=>card(x,'pieces',ownedP.has(x[0]),me.inventory.selectedPieces===x[0])).join('')}</div></div>`);$$('[data-buy-type]').forEach(b=>b.onclick=()=>shopBuy(b.dataset.buyType,b.dataset.buyId));$$('[data-select-type]').forEach(b=>b.onclick=()=>shopSelect(b.dataset.selectType,b.dataset.selectId))}
async function shopBuy(type,id){try{const j=await api('/api/shop/buy',{method:'POST',body:JSON.stringify({uid:accountId,type,itemId:id})});me=j.user;openShop()}catch(e){alert(e.message)}}
async function shopSelect(type,id){try{const j=await api('/api/shop/select',{method:'POST',body:JSON.stringify({uid:accountId,type,itemId:id})});me=j.user;openShop()}catch(e){alert(e.message)}}
async function openAdmin(){const pass=prompt('Пароль администратора');if(pass===null)return;try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:pass})});renderAdmin(pass)}catch(e){alert('Неверный пароль')}}
async function renderAdmin(pass){const j=await api('/api/admin/players?password='+encodeURIComponent(pass));openModal(`<div class="admin"><h2>🛡 Админ-панель</h2><div class="admin-danger"><button id="clearDB">🗑 Полностью очистить базу</button></div><div class="admin-list">${j.players.length?j.players.map(u=>`<div class="admin-user"><div><b>${escapeHtml(u.name)}</b><small>${u.id}<br>🪙 ${u.chips} ${u.vip?'• VIP':''} ${u.banned?'• БАН':''}</small></div><div class="admin-actions"><button data-admin="chips" data-id="${u.id}">+Фишки</button><button data-admin="vip" data-id="${u.id}">${u.vip?'VIP OFF':'VIP'}</button><button data-admin="ban" data-id="${u.id}">${u.banned?'Разбан':'Бан'}</button></div></div>`).join(''):'<p>Игроков пока нет.</p>'}</div></div>`);$('#clearDB').onclick=async()=>{if(!confirm('Удалить ВСЕ аккаунты и комнаты?'))return;try{await api('/api/admin/action',{method:'POST',body:JSON.stringify({password:pass,action:'clear_database'})});alert('База очищена');location.reload()}catch(e){alert(e.message)}};$$('[data-admin]').forEach(b=>b.onclick=async()=>{try{const action=b.dataset.admin,id=b.dataset.id,body={password:pass,action,userId:id};if(action==='chips'){const amount=Number(prompt('Сколько фишек начислить?','1000'));if(!Number.isFinite(amount))return;body.amount=amount}else if(action==='vip'){body.value=b.textContent==='VIP OFF'?false:true}else if(action==='ban'){body.value=b.textContent==='Бан'}await api('/api/admin/action',{method:'POST',body:JSON.stringify(body)});renderAdmin(pass)}catch(e){alert(e.message)}})}
function profileModal(){openModal(`<div class="profile"><h2>👤 Профиль</h2><p><b>${escapeHtml(me.name)}</b>${me.vip?' <span class="vip">VIP</span>':''}</p><div class="profile-stat">🪙 <b>${me.chips}</b> фишек</div><p>Аккаунт сохранён на сервере.</p></div>`)}
function authActions(){$$('[data-action]').forEach(b=>b.disabled=true);$('#shopBtn')?.addEventListener('click',openShop);$('#profileBtn')?.addEventListener('click',profileModal);$('#adminBtn')?.addEventListener('click',openAdmin);$('#hintBtn')?.addEventListener('click',requestHint);authenticate()}
$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='rules')openModal(RULES_HTML);else if(a==='about')openModal(ABOUT_HTML);else if(a==='computer')openBotMenu();else if(a==='local')startGame('local');else if(a==='shop')openShop();else startGame('online')});
setInterval(()=>{if(mode==='online'&&!$('#game').hidden)syncOnline()},2000);setInterval(async()=>{if(!accountId)return;try{const j=await api(`/api/state?uid=${accountId}`);const wasVip=!!me?.vip;me=j.user;store=j.store;if(wasVip!==!!me.vip){if(!me.vip&&me.inventory.selectedBoard==='vip_jewel')me.inventory.selectedBoard='classic';if(!me.vip&&me.inventory.selectedPieces==='vip_gem')me.inventory.selectedPieces='classic';render();}}catch(e){}},3000);setInterval(()=>{if(!$('#game').hidden&&state&&mode!=='online'&&gameTimer==null){gameTimer=setInterval(render,1000)}},1000);

document.addEventListener('DOMContentLoaded',authActions);
