const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DB_FILE=path.join(ROOT,'db.json');
const rooms=new Map(),PLAYER_TIMEOUT=15000,ROOM_TTL=60*60*1000,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'admin123';
const STORE_BOARDS=[['classic','Классика','Дерево и латунь',0],['emerald','Emerald','Изумрудный камень',300],['midnight','Midnight','Ночной обсидиан',450],['royal','Royal','Королевское золото',600],['ice','Ice','Ледяной кристалл',750]];
const STORE_PIECES=[['classic','Classic','Классические фигуры',0],['neo','Neo','Современный минимализм',250],['royal','Royal','Премиальные золотые',450],['glass','Glass','Стеклянные фигуры',650],['neon','Neon','Неоновый стиль',800]];
function uid(){return crypto.randomBytes(16).toString('hex')} function now(){return Date.now()}
function json(res,code,data){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function sanitizeName(v){return String(v||'').replace(/[<>]/g,'').trim().slice(0,24)}
function freshDB(){return {users:{},leaderboard:[]}}
function loadDB(){try{const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));return d&&d.users?d:freshDB()}catch{return freshDB()}}
let db=loadDB();
function saveDB(){const tmp=DB_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB_FILE)}
function userView(u){return {id:u.id,name:u.name,chips:u.chips,inventory:u.inventory,vip:!!u.vip,banned:!!u.banned,createdAt:u.createdAt,updatedAt:u.updatedAt}}
function getUser(id){return id&&db.users[id]}
function requireUser(id){const u=getUser(id);if(!u)throw Error('Игрок не авторизован');if(u.banned)throw Error('Пользователь заблокирован');return u}
function ensureUser(id,name){let u=getUser(id);if(!u){u={id:id||uid(),name:sanitizeName(name),chips:1000,inventory:{boards:['classic'],pieces:['classic'],selectedBoard:'classic',selectedPieces:'classic'},vip:false,banned:false,createdAt:now(),updatedAt:now()};db.users[u.id]=u;saveDB()}return u}
function sanitizeRoom(room,uid){return {id:room.id,status:room.status,turn:room.turn,players:Object.values(room.players).map(p=>({uid:p.uid,name:p.name,side:p.side,online:now()-p.lastSeen<PLAYER_TIMEOUT})),fen:room.fen,clocks:room.clocks,result:room.result,winner:room.winner,drawReason:room.drawReason,lastMove:room.lastMove,moveNumber:room.moveNumber,chat:room.chat.slice(-30),stake:room.stake,bank:room.bank,selfSide:room.players[uid]?.side||null}}
const START_FEN='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',KNIGHT=[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]],KING=[[1,1],[1,0],[1,-1],[0,1],[0,-1],[-1,1],[-1,0],[-1,-1]];
function fileOf(s){return s%8}function rankOf(s){return Math.floor(s/8)}function idx(f,r){return r*8+f}function colorOf(p){return !p?null:p===p.toUpperCase()?'w':'b'}function enemy(c){return c==='w'?'b':'w'}
function parseFen(f){const [placement,side,castling,ep,half,full]=f.split(/\s+/),board=Array(64).fill(null);let r=7,ff=0;for(const ch of placement){if(ch==='/'){r--;ff=0}else if(/[1-8]/.test(ch))ff+=+ch;else board[idx(ff++,r)]=ch}return{board,side,castling:castling==='-'?'':castling,ep:ep==='-'?null:ep.charCodeAt(0)-97+8*(+ep[1]-1),half:+half||0,full:+full||1,history:[]}}
function fen(st){let p='';for(let r=7;r>=0;r--){let e=0;for(let f=0;f<8;f++){const x=st.board[idx(f,r)];if(!x)e++;else{if(e){p+=e;e=0}p+=x}}if(e)p+=e;if(r)p+='/'}return `${p} ${st.side} ${st.castling||'-'} ${st.ep==null?'-':String.fromCharCode(97+fileOf(st.ep))+(rankOf(st.ep)+1)} ${st.half} ${st.full}`}
function clone(s){return{board:s.board.slice(),side:s.side,castling:s.castling,ep:s.ep,half:s.half,full:s.full,history:s.history.slice()}}function squareName(s){return String.fromCharCode(97+fileOf(s))+(rankOf(s)+1)}
function isAttacked(st,s,by){const f=fileOf(s),r=rankOf(s),pawn=by==='w'?'P':'p',pr=by==='w'?r-1:r+1;if(pr>=0&&pr<8)for(const df of[-1,1]){const F=f+df;if(F>=0&&F<8&&st.board[idx(F,pr)]===pawn)return true}const kn=by==='w'?'N':'n';for(const[dF,dR]of KNIGHT){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[idx(F,R)]===kn)return true}const ki=by==='w'?'K':'k';for(const[dF,dR]of KING){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[idx(F,R)]===ki)return true}for(const[dF,dR]of[[1,0],[-1,0],[0,1],[0,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[idx(F,R)];if(p){if(colorOf(p)===by&&'rq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}for(const[dF,dR]of[[1,1],[1,-1],[-1,1],[-1,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[idx(F,R)];if(p){if(colorOf(p)===by&&'bq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}return false}
function kingSquare(st,c){return st.board.findIndex(p=>p===(c==='w'?'K':'k'))}function inCheck(st,c){const k=kingSquare(st,c);return k<0||isAttacked(st,k,enemy(c))}
function pseudoMoves(st){const c=st.side,m=[],add=(from,to,x={})=>m.push({from,to,...x});for(let from=0;from<64;from++){const p=st.board[from];if(!p||colorOf(p)!==c)continue;const f=fileOf(from),r=rankOf(from),u=p.toUpperCase();if(u==='P'){const d=c==='w'?1:-1,sr=c==='w'?1:6,pr=c==='w'?7:0,rr=r+d;if(rr>=0&&rr<8){const one=idx(f,rr);if(!st.board[one]){if(rr===pr)for(const q of['Q','R','B','N'])add(from,one,{promotion:c==='w'?q:q.toLowerCase()});else add(from,one);if(r===sr){const two=idx(f,r+2*d);if(!st.board[two])add(from,two)}}for(const df of[-1,1]){const F=f+df;if(F<0||F>7)continue;const to=idx(F,rr),t=st.board[to];if(t&&colorOf(t)!==c){if(rr===pr)for(const q of['Q','R','B','N'])add(from,to,{promotion:c==='w'?q:q.toLowerCase()});else add(from,to)}if(st.ep===to)add(from,to,{ep:true})}}}else if(u==='N'){for(const[dF,dR]of KNIGHT){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t||colorOf(t)!==c)add(from,to)}}}else if(u==='K'){for(const[dF,dR]of KING){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t||colorOf(t)!==c)add(from,to)}}const rr=c==='w'?0:7;if(from===idx(4,rr)&&!inCheck(st,c)){const K=c==='w'?'K':'k',Q=c==='w'?'Q':'q';if(st.castling.includes(K)&&st.board[idx(7,rr)]===(c==='w'?'R':'r')&&!st.board[idx(5,rr)]&&!st.board[idx(6,rr)]&&!isAttacked(st,idx(5,rr),enemy(c))&&!isAttacked(st,idx(6,rr),enemy(c)))add(from,idx(6,rr),{castle:'K'});if(st.castling.includes(Q)&&st.board[idx(0,rr)]===(c==='w'?'R':'r')&&!st.board[idx(1,rr)]&&!st.board[idx(2,rr)]&&!st.board[idx(3,rr)]&&!isAttacked(st,idx(3,rr),enemy(c))&&!isAttacked(st,idx(2,rr),enemy(c)))add(from,idx(2,rr),{castle:'Q'})}}else{const ds=u==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:u==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const[dF,dR]of ds){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t)add(from,to);else{if(colorOf(t)!==c)add(from,to);break}F+=dF;R+=dR}}}}return m}
function applyMove(st,m){const n=clone(st),p=n.board[m.from],c=n.side,u=p.toUpperCase(),target=n.board[m.to];n.board[m.from]=null;if(m.ep)n.board[m.to+(c==='w'?-8:8)]=null;n.board[m.to]=m.promotion||p;if(m.castle){const rr=c==='w'?0:7;if(m.castle==='K'){n.board[idx(5,rr)]=n.board[idx(7,rr)];n.board[idx(7,rr)]=null}else{n.board[idx(3,rr)]=n.board[idx(0,rr)];n.board[idx(0,rr)]=null}}if(u==='K')n.castling=n.castling.replace(c==='w'?/[KQ]/g:/[kq]/g,'');if(u==='R'){if(m.from===0)n.castling=n.castling.replace('Q','');if(m.from===7)n.castling=n.castling.replace('K','');if(m.from===56)n.castling=n.castling.replace('q','');if(m.from===63)n.castling=n.castling.replace('k','')}if(target?.toUpperCase()==='R'){if(m.to===0)n.castling=n.castling.replace('Q','');if(m.to===7)n.castling=n.castling.replace('K','');if(m.to===56)n.castling=n.castling.replace('q','');if(m.to===63)n.castling=n.castling.replace('k','')}n.ep=null;if(u==='P'&&Math.abs(m.to-m.from)===16)n.ep=(m.to+m.from)/2;n.half=(u==='P'||target||m.ep)?0:n.half+1;if(c==='b')n.full++;n.side=enemy(c);return n}
function legalMoves(st){return pseudoMoves(st).filter(m=>!inCheck(applyMove(st,m),st.side))}function effectiveEp(st){if(st.ep==null)return'-';return pseudoMoves(st).some(m=>m.ep)?squareName(st.ep):'-'}function positionKey(st){return st.board.map(x=>x||'.').join('')+'|'+st.side+'|'+(st.castling||'-')+'|'+effectiveEp(st)}
function isDead(st){const ps=[];for(let i=0;i<64;i++){const p=st.board[i];if(p&&p.toUpperCase()!=='K')ps.push({p:p.toUpperCase(),s:i})}if(!ps.length)return true;if(ps.some(x=>['P','R','Q'].includes(x.p)))return false;if(ps.length===1)return true;if(ps.length===2&&ps.every(x=>x.p==='B'))return ((fileOf(ps[0].s)+rankOf(ps[0].s))%2)===((fileOf(ps[1].s)+rankOf(ps[1].s))%2);return false}
function gameStatus(st){const ms=legalMoves(st);if(!ms.length)return inCheck(st,st.side)?(st.side==='w'?'0-1':'1-0'):'1/2-1/2';if(st.half>=150||isDead(st))return'1/2-1/2';const k=positionKey(st),n=1+st.history.filter(x=>x===k).length;return n>=5?'1/2-1/2':null}
function parseMove(st,from,to,promotion){return legalMoves(st).find(x=>x.from===from&&x.to===to&&(x.promotion||'')===(promotion||''))||null}
function stateFromFen(f){const s=parseFen(f);s.history=[positionKey(s)];return s}
function moveRecord(m,st){return{from:squareName(m.from),to:squareName(m.to),promotion:m.promotion?m.promotion.toUpperCase():null,castle:m.castle||null,ep:!!m.ep}}
function createRoom(user,stake){const id=crypto.randomBytes(3).toString('hex').toUpperCase();const s=Math.max(0,Math.min(100000,Number(stake)||0));rooms.set(id,{id,status:'waiting',players:{},createdAt:now(),lastActivity:now(),fen:START_FEN,turn:'w',clocks:{w:600000,b:600000},lastTick:now(),result:null,winner:null,drawReason:null,lastMove:null,moveNumber:1,chat:[],stake:s,bank:0});return rooms.get(id)}
function activePlayers(room){return Object.values(room.players).filter(p=>now()-p.lastSeen<PLAYER_TIMEOUT)}
function tickClock(room){if(room.status!=='playing'||room.result)return;const dt=Math.max(0,now()-room.lastTick);room.clocks[room.turn]=Math.max(0,room.clocks[room.turn]-dt);room.lastTick=now();if(room.clocks[room.turn]===0){room.result=room.turn==='w'?'0-1':'1-0';room.winner=room.turn==='w'?'b':'w';room.status='finished';settleWinner(room)}}
function settleWinner(room){if(!room.winner||room.paid)return;const p=Object.values(room.players).find(x=>x.side===room.winner);if(p){const u=getUser(p.accountId);if(u){u.chips+=room.bank;u.updatedAt=now();saveDB()}}room.paid=true}
function settleDraw(room){if(room.paid)return;const ps=Object.values(room.players);if(ps.length){const each=Math.floor(room.bank/ps.length);for(const p of ps){const u=getUser(p.uid);if(u){u.chips+=each;u.updatedAt=now()}}saveDB()}room.paid=true}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true});
try{
if(req.method==='POST'&&p==='/api/auth'){const b=await readBody(req),id=sanitizeName(b.id)||uid(),name=sanitizeName(b.name);let user=getUser(id);if(!user){if(!name)return json(res,200,{ok:true,needsName:true});user=ensureUser(id,name)}else if(name&&user.name!==name){user.name=name;user.updatedAt=now();saveDB()}if(user.banned)return json(res,403,{ok:false,error:'Пользователь заблокирован'});return json(res,200,{ok:true,user:userView(user),needsName:false,store:{boards:STORE_BOARDS,pieces:STORE_PIECES}})}
if(req.method==='GET'&&p==='/api/state'){const user=requireUser(u.searchParams.get('uid'));return json(res,200,{ok:true,user:userView(user),store:{boards:STORE_BOARDS,pieces:STORE_PIECES}})}
if(req.method==='POST'&&p==='/api/shop/buy'){const b=await readBody(req),user=requireUser(b.uid),type=b.type,id=String(b.itemId||'');const arr=type==='board'?STORE_BOARDS:type==='pieces'?STORE_PIECES:null;if(!arr)return json(res,400,{ok:false,error:'Неверный тип товара'});const item=arr.find(x=>x[0]===id);if(!item)return json(res,404,{ok:false,error:'Товар не найден'});const inv=type==='board'?user.inventory.boards:user.inventory.pieces;if(inv.includes(id))return json(res,200,{ok:true,user:userView(user),message:'Уже куплено'});if(user.chips<item[3])return json(res,400,{ok:false,error:'Недостаточно фишек'});user.chips-=item[3];inv.push(id);user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/shop/select'){const b=await readBody(req),user=requireUser(b.uid);if(b.type==='board'&&user.inventory.boards.includes(b.itemId))user.inventory.selectedBoard=b.itemId;else if(b.type==='pieces'&&user.inventory.pieces.includes(b.itemId))user.inventory.selectedPieces=b.itemId;else return json(res,400,{ok:false,error:'Предмет не куплен'});user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/admin/login'){const b=await readBody(req);return json(res,b.password===ADMIN_PASSWORD?200:401,{ok:b.password===ADMIN_PASSWORD})}
if(req.method==='GET'&&p==='/api/admin/players'){if(u.searchParams.get('password')!==ADMIN_PASSWORD)return json(res,401,{ok:false,error:'Доступ запрещён'});return json(res,200,{ok:true,players:Object.values(db.users).map(userView)})}
if(req.method==='POST'&&p==='/api/admin/action'){const b=await readBody(req);if(b.password!==ADMIN_PASSWORD)return json(res,401,{ok:false,error:'Доступ запрещён'});if(b.action==='clear_database'){db=freshDB();saveDB();rooms.clear();return json(res,200,{ok:true})}const user=getUser(b.userId);if(!user)return json(res,404,{ok:false,error:'Игрок не найден'});if(b.action==='chips'){user.chips=Math.max(0,user.chips+Number(b.amount||0))}else if(b.action==='vip')user.vip=!!b.value;else if(b.action==='ban')user.banned=!!b.value;else return json(res,400,{ok:false,error:'Неизвестное действие'});user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/create'){const b=await readBody(req),user=requireUser(b.uid),stake=Math.max(0,Math.floor(Number(b.stake)||0));if(user.chips<stake)return json(res,400,{ok:false,error:'Недостаточно фишек для ставки'});user.chips-=stake;saveDB();const room=createRoom(user,stake),id=uid();room.players[id]={uid:id,name:user.name,side:'w',lastSeen:now(),accountId:user.id};room.bank=stake;return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),self:'w',user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/join'){const b=await readBody(req),user=requireUser(b.uid),room=rooms.get(String(b.roomId||'').toUpperCase());if(!room)return json(res,404,{ok:false,error:'Комната не найдена'});if(Object.keys(room.players).length>=2||room.status!=='waiting')return json(res,400,{ok:false,error:'Комната недоступна'});if(user.chips<room.stake)return json(res,400,{ok:false,error:'Недостаточно фишек для ставки'});user.chips-=room.stake;saveDB();const id=uid();room.players[id]={uid:id,name:user.name,side:'b',lastSeen:now(),accountId:user.id};room.bank+=room.stake;room.status='playing';room.lastActivity=now();room.lastTick=now();return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),self:'b',user:userView(user)})}
const m=/^\/api\/room\/(sync|move|leave|chat|heartbeat)$/.exec(p);if(m){const b=req.method==='GET'?Object.fromEntries(u.searchParams.entries()):await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase()),player=room?.players?.[b.uid];if(!room||!player)return json(res,404,{ok:false,error:'Сессия не найдена'});requireUser(player.accountId);player.lastSeen=now();room.lastActivity=now();tickClock(room);if(m[1]==='sync'||m[1]==='heartbeat')return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side});if(m[1]==='chat'){const text=String(b.text||'').replace(/[<>]/g,'').slice(0,160);if(text)room.chat.push({uid:player.accountId,name:player.name,text,ts:now()});return json(res,200,{ok:true})}if(m[1]==='leave'){delete room.players[player.uid];if(room.status==='waiting'){const u=getUser(player.accountId);if(u){u.chips+=room.stake;saveDB()}room.status='finished';room.result='cancelled'}else if(room.status==='playing'){if(Object.keys(room.players).length===1){room.winner=Object.values(room.players)[0].side;room.result=room.winner==='w'?'1-0':'0-1';room.status='finished';settleWinner(room)}else if(!Object.keys(room.players).length){room.status='finished';room.result='cancelled';settleDraw(room)}}return json(res,200,{ok:true})}if(m[1]==='move'){if(room.status!=='playing'||room.result)return json(res,400,{ok:false,error:'Игра завершена'});if(player.side!==room.turn)return json(res,400,{ok:false,error:'Сейчас ход соперника'});const st=stateFromFen(room.fen),mv=parseMove(st,Number(b.from),Number(b.to),b.promotion||null);if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});const n=applyMove(st,mv);n.history=st.history.concat(positionKey(n));const status=gameStatus(n);room.fen=fen(n);room.turn=n.side;room.moveNumber=n.full;room.lastMove=moveRecord(mv,st);room.lastTick=now();if(status){room.result=status;room.status='finished';if(status==='1-0')room.winner='w';else if(status==='0-1')room.winner='b';else room.drawReason='Правила ничьей / пат';if(room.winner)settleWinner(room);else settleDraw(room)}return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side})}}
}catch(e){return json(res,400,{ok:false,error:e.message})}
if(req.method==='GET'){const file=p==='/'?'/index.html':p,fp=path.normalize(path.join(PUBLIC,file));if(!fp.startsWith(PUBLIC))return json(res,403,{error:'forbidden'});if(!fs.existsSync(fp))return json(res,404,{error:'not found'});const ext=path.extname(fp),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(fp).pipe(res);return}return json(res,404,{error:'not found'})}
setInterval(()=>{for(const room of rooms.values()){tickClock(room);if(room.status==='playing'&&activePlayers(room).length===0){room.status='finished';room.result='cancelled';settleDraw(room)}if(now()-room.lastActivity>ROOM_TTL)rooms.delete(room.id)}},1000);
if(require.main===module)http.createServer((req,res)=>route(req,res)).listen(PORT,()=>console.log(`SANI CHESS server: http://localhost:${PORT}`));
module.exports={parseFen,fen,legalMoves,applyMove,positionKey,gameStatus,START_FEN};
