const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');

const PORT=Number(process.env.PORT||3000);
const ROOT=__dirname;
const PUBLIC=path.join(ROOT,'public');
const DB_FILE=path.join(ROOT,'db.json');
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'admin123';
const PLAYER_TIMEOUT=15000;
const ROOM_TTL=2*60*60*1000;

const STORE_BOARDS=[
 ['classic','Классика','Дерево и латунь',0],
 ['emerald','Emerald','Изумрудный камень',30000],
 ['midnight','Midnight','Ночной обсидиан',45000],
 ['royal','Royal','Королевское золото',60000],
 ['ice','Ice','Ледяной кристалл',75000]
];
const STORE_PIECES=[
 ['classic','Classic','Классические фигуры',0],
 ['neo','Neo','Современный минимализм',25000],
 ['royal','Royal','Премиальные золотые',45000],
 ['glass','Glass','Стеклянные фигуры',65000],
 ['neon','Neon','Неоновый стиль',80000]
];
const BOTS={
 kettle:{name:'Чайник',difficulty:'easy',depth:1},
 player:{name:'Шпилер',difficulty:'medium',depth:2},
 maestro:{name:'Маэстро',difficulty:'hard',depth:3}
};
const RANKS=[
 {level:1,name:'Новичок',wins:0},
 {level:2,name:'Ученик',wins:3},
 {level:3,name:'Любитель',wins:10},
 {level:4,name:'Игрок',wins:25},
 {level:5,name:'Сильный игрок',wins:50},
 {level:6,name:'Эксперт',wins:100},
 {level:7,name:'Мастер',wins:250},
 {level:8,name:'Гроссмейстер',wins:500}
];

const START_FEN='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
const KNIGHT=[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]];
const KING=[[1,1],[1,0],[1,-1],[0,1],[0,-1],[-1,1],[-1,0],[-1,-1]];
const VAL={P:100,N:320,B:330,R:500,Q:900,K:20000};
const rooms=new Map();

function uid(){return crypto.randomBytes(16).toString('hex')}
function now(){return Date.now()}
function json(res,code,data){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
function html(res,file){res.writeHead(200,{'Content-Type':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.js')?'application/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-cache'});res.end(fs.readFileSync(file))}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function sanitizeName(v){return String(v||'').replace(/[<>]/g,'').trim().slice(0,24)}
function freshDB(){return {users:{},leaderboard:[]}}
function loadDB(){try{const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));if(d&&d.users)return d}catch{}return freshDB()}
let db=loadDB();
function saveDB(){const tmp=DB_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB_FILE)}
function rankFor(wins){let r=RANKS[0];for(const x of RANKS)if(wins>=x.wins)r=x;return r}
function userView(u){const r=rankFor(u.wins||0);return {id:u.id,name:u.name,chips:u.chips,inventory:u.inventory,vip:!!u.vip,banned:!!u.banned,wins:u.wins||0,losses:u.losses||0,draws:u.draws||0,rank:r,createdAt:u.createdAt,updatedAt:u.updatedAt}}
function getUser(id){return id&&db.users[id]}
function requireUser(id){const u=getUser(id);if(!u)throw Error('Игрок не авторизован');if(u.banned)throw Error('Пользователь заблокирован');return u}
function ensureUser(id,name){let u=getUser(id);if(!u){u={id:id||uid(),name:sanitizeName(name)||'Игрок',chips:100000,inventory:{boards:['classic'],pieces:['classic'],selectedBoard:'classic',selectedPieces:'classic'},vip:false,banned:false,wins:0,losses:0,draws:0,createdAt:now(),updatedAt:now()};db.users[u.id]=u;saveDB()}return u}
function finishStats(winnerId,loserId,drawIds=[]){if(winnerId){const w=getUser(winnerId);if(w){w.wins=(w.wins||0)+1;w.updatedAt=now()}}if(loserId){const l=getUser(loserId);if(l){l.losses=(l.losses||0)+1;l.updatedAt=now()}}for(const id of drawIds){const u=getUser(id);if(u){u.draws=(u.draws||0)+1;u.updatedAt=now()}}saveDB()}
function fileOf(s){return s%8} function rankOf(s){return Math.floor(s/8)} function idx(f,r){return r*8+f}
function colorOf(p){return p?p===p.toUpperCase()?'w':'b':null} function enemy(c){return c==='w'?'b':'w'}
function parseFen(fenText){const [placement,side,castling,ep,half,full]=fenText.split(/\s+/),board=Array(64).fill(null);let r=7,file=0;for(const ch of placement){if(ch==='/'){r--;file=0}else if(/[1-8]/.test(ch))file+=+ch;else board[idx(file++,r)]=ch}return{board,side,castling:castling==='-'?'':castling,ep:ep==='-'?null:ep.charCodeAt(0)-97+8*(+ep[1]-1),half:+half||0,full:+full||1,history:[]}}
function fen(st){let p='';for(let r=7;r>=0;r--){let e=0;for(let f=0;f<8;f++){const x=st.board[idx(f,r)];if(!x)e++;else{if(e){p+=e;e=0}p+=x}}if(e)p+=e;if(r)p+='/'}return `${p} ${st.side} ${st.castling||'-'} ${st.ep==null?'-':String.fromCharCode(97+fileOf(st.ep))+(rankOf(st.ep)+1)} ${st.half} ${st.full}`}
function clone(s){return{board:s.board.slice(),side:s.side,castling:s.castling,ep:s.ep,half:s.half,full:s.full,history:s.history.slice()}}
function squareName(s){return String.fromCharCode(97+fileOf(s))+(rankOf(s)+1)}
function isAttacked(st,s,by){const f=fileOf(s),r=rankOf(s),pawn=by==='w'?'P':'p',pr=by==='w'?r-1:r+1;if(pr>=0&&pr<8)for(const df of[-1,1]){const F=f+df;if(F>=0&&F<8&&st.board[idx(F,pr)]===pawn)return true}const kn=by==='w'?'N':'n';for(const[dF,dR]of KNIGHT){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[idx(F,R)]===kn)return true}const ki=by==='w'?'K':'k';for(const[dF,dR]of KING){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[idx(F,R)]===ki)return true}for(const[dF,dR]of[[1,0],[-1,0],[0,1],[0,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[idx(F,R)];if(p){if(colorOf(p)===by&&'rq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}for(const[dF,dR]of[[1,1],[1,-1],[-1,1],[-1,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[idx(F,R)];if(p){if(colorOf(p)===by&&'bq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}return false}
function kingSquare(st,c){return st.board.findIndex(p=>p===(c==='w'?'K':'k'))}
function inCheck(st,c){const k=kingSquare(st,c);return k<0||isAttacked(st,k,enemy(c))}
function pseudoMoves(st){const c=st.side,m=[],add=(from,to,x={})=>m.push({from,to,...x});for(let from=0;from<64;from++){const p=st.board[from];if(!p||colorOf(p)!==c)continue;const f=fileOf(from),r=rankOf(from),u=p.toUpperCase();if(u==='P'){const d=c==='w'?1:-1,sr=c==='w'?1:6,pr=c==='w'?7:0,rr=r+d;if(rr>=0&&rr<8){const one=idx(f,rr);if(!st.board[one]){if(rr===pr)for(const q of['Q','R','B','N'])add(from,one,{promotion:c==='w'?q:q.toLowerCase()});else add(from,one);if(r===sr){const two=idx(f,r+2*d);if(!st.board[two])add(from,two)}}for(const df of[-1,1]){const F=f+df;if(F<0||F>7)continue;const to=idx(F,rr),t=st.board[to];if(t&&colorOf(t)!==c){if(rr===pr)for(const q of['Q','R','B','N'])add(from,to,{promotion:c==='w'?q:q.toLowerCase()});else add(from,to)}if(st.ep===to){const epPawn=st.board[to+(c==='w'?-8:8)];if(epPawn=== (c==='w'?'p':'P'))add(from,to,{ep:true})}}}}else if(u==='N'){for(const[dF,dR]of KNIGHT){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t||colorOf(t)!==c)add(from,to)}}}else if(u==='K'){for(const[dF,dR]of KING){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t||colorOf(t)!==c)add(from,to)}}const rr=c==='w'?0:7;if(from===idx(4,rr)&&!inCheck(st,c)){const K=c==='w'?'K':'k',Q=c==='w'?'Q':'q';if(st.castling.includes(K)&&st.board[idx(7,rr)]===(c==='w'?'R':'r')&&!st.board[idx(5,rr)]&&!st.board[idx(6,rr)]&&!isAttacked(st,idx(5,rr),enemy(c))&&!isAttacked(st,idx(6,rr),enemy(c)))add(from,idx(6,rr),{castle:'K'});if(st.castling.includes(Q)&&st.board[idx(0,rr)]===(c==='w'?'R':'r')&&!st.board[idx(1,rr)]&&!st.board[idx(2,rr)]&&!st.board[idx(3,rr)]&&!isAttacked(st,idx(3,rr),enemy(c))&&!isAttacked(st,idx(2,rr),enemy(c)))add(from,idx(2,rr),{castle:'Q'})}}else{const ds=u==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:u==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const[dF,dR]of ds){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t)add(from,to);else{if(colorOf(t)!==c&&t.toUpperCase()!=='K')add(from,to);break}F+=dF;R+=dR}}}}return m}
function applyMove(st,m){const n=clone(st),p=n.board[m.from],c=n.side,u=p.toUpperCase(),target=n.board[m.to];n.board[m.from]=null;if(m.ep)n.board[m.to+(c==='w'?-8:8)]=null;n.board[m.to]=m.promotion||p;if(m.castle){const rr=c==='w'?0:7;if(m.castle==='K'){n.board[idx(5,rr)]=n.board[idx(7,rr)];n.board[idx(7,rr)]=null}else{n.board[idx(3,rr)]=n.board[idx(0,rr)];n.board[idx(0,rr)]=null}}if(u==='K')n.castling=n.castling.replace(c==='w'?/[KQ]/g:/[kq]/g,'');if(u==='R'){if(m.from===0)n.castling=n.castling.replace('Q','');if(m.from===7)n.castling=n.castling.replace('K','');if(m.from===56)n.castling=n.castling.replace('q','');if(m.from===63)n.castling=n.castling.replace('k','')}if(target?.toUpperCase()==='R'){if(m.to===0)n.castling=n.castling.replace('Q','');if(m.to===7)n.castling=n.castling.replace('K','');if(m.to===56)n.castling=n.castling.replace('q','');if(m.to===63)n.castling=n.castling.replace('k','')}n.ep=null;if(u==='P'&&Math.abs(m.to-m.from)===16)n.ep=(m.from+m.to)/2;n.half=(u==='P'||target||m.ep)?0:n.half+1;if(c==='b')n.full++;n.side=enemy(c);return n}
function legalMoves(st){return pseudoMoves(st).filter(m=>!inCheck(applyMove(st,m),st.side))}
function effectiveEp(st){if(st.ep==null)return'-';return pseudoMoves(st).some(m=>m.ep)?squareName(st.ep):'-'}
function positionKey(st){return st.board.map(x=>x||'.').join('')+'|'+st.side+'|'+(st.castling||'-')+'|'+effectiveEp(st)}
function isDead(st){const ps=[];for(let i=0;i<64;i++){const p=st.board[i];if(p&&p.toUpperCase()!=='K')ps.push({p:p.toUpperCase(),s:i})}if(!ps.length)return true;if(ps.some(x=>['P','R','Q'].includes(x.p)))return false;if(ps.length===1)return true;if(ps.length===2&&ps.every(x=>x.p==='B'))return ((fileOf(ps[0].s)+rankOf(ps[0].s))%2)===((fileOf(ps[1].s)+rankOf(ps[1].s))%2);return false}
function gameStatus(st){const ms=legalMoves(st);if(!ms.length)return inCheck(st,st.side)?(st.side==='w'?'0-1':'1-0'):'1/2-1/2';if(st.half>=150||isDead(st))return'1/2-1/2';const n=1+st.history.filter(x=>x===positionKey(st)).length;return n>=5?'1/2-1/2':null}
function parseMove(st,from,to,promotion){return legalMoves(st).find(x=>x.from===from&&x.to===to&&(x.promotion||'')===(promotion||''))||null}
function stateFromFen(f,history){const s=parseFen(f);s.history=Array.isArray(history)&&history.length?history.slice():[positionKey(s)];return s}
function moveRecord(m,st){return{from:squareName(m.from),to:squareName(m.to),promotion:m.promotion?m.promotion.toUpperCase():null,castle:m.castle||null,ep:!!m.ep}}
function evaluate(st){let score=0;for(const p of st.board)if(p)score+=(colorOf(p)==='w'?1:-1)*VAL[p.toUpperCase()];return score+(legalMoves(st).length*(st.side==='w'?2:-2))}
function aiSearch(st,depth,alpha,beta){const ms=legalMoves(st);if(depth<=0||!ms.length){if(!ms.length){if(inCheck(st,st.side))return st.side==='w'?-200000:200000;return 0}return evaluate(st)}if(st.side==='w'){let best=-Infinity;for(const m of ms){const sc=aiSearch(applyMove(st,m),depth-1,alpha,beta);if(sc>best)best=sc;if(best>alpha)alpha=best;if(alpha>=beta)break}return best}else{let best=Infinity;for(const m of ms){const sc=aiSearch(applyMove(st,m),depth-1,alpha,beta);if(sc<best)best=sc;if(best<beta)beta=best;if(alpha>=beta)break}return best}}
function botMove(st,key){const bot=BOTS[key]||BOTS.player;const ms=legalMoves(st);if(!ms.length)return null;let best=Infinity,bestMoves=[];for(const m of ms){const sc=aiSearch(applyMove(st,m),bot.depth-1,-Infinity,Infinity);if(sc<best){best=sc;bestMoves=[m]}else if(sc===best)bestMoves.push(m)}return bestMoves[Math.floor(Math.random()*bestMoves.length)]}
function newRoomId(){for(let i=0;i<1000;i++){const id=String(Math.floor(1000+Math.random()*9000));if(!rooms.has(id))return id}throw Error('Не удалось создать номер стола')}
function baseRoom(id,stake){return{id,status:'waiting',players:{},createdAt:now(),lastActivity:now(),fen:START_FEN,history:[positionKey(parseFen(START_FEN))],turn:'w',clocks:{w:600000,b:600000},lastTick:now(),result:null,winner:null,drawReason:null,lastMove:null,moveNumber:1,chat:[],stake,bank:0,paid:false,drawOfferBy:null,kind:'online',botKey:null,playerUid:null,statsDone:false,rematch:{deadline:0,requests:{},closed:false}}}
function tickClock(room){if(room.status!=='playing'||room.result)return;const dt=Math.max(0,now()-room.lastTick);room.clocks[room.turn]=Math.max(0,room.clocks[room.turn]-dt);room.lastTick=now();if(room.clocks[room.turn]===0){room.result=room.turn==='w'?'0-1':'1-0';room.winner=room.turn==='w'?'b':'w';room.status='finished';settleRoom(room)}}
function settleRoom(room){if(room.paid)return;const ps=Object.values(room.players);if(room.kind==='bot'){const p=ps[0];const u=p&&getUser(p.accountId);if(u){if(room.winner==='w')u.chips+=room.bank;else if(!room.winner)u.chips+=room.stake;u.updatedAt=now();saveDB();if(room.winner==='w')finishStats(u.id,null);else if(room.result==='0-1')finishStats(null,u.id);else finishStats(null,null,[u.id])}}else{const winner=ps.find(p=>p.side===room.winner);if(winner){const u=getUser(winner.accountId);if(u){u.chips+=room.bank;u.updatedAt=now();saveDB()}const loser=ps.find(p=>p.side!==room.winner);finishStats(winner.accountId,loser?.accountId)}else finishStats(null,null,ps.map(p=>p.accountId));if(!winner&&ps.length){const each=Math.floor(room.bank/ps.length);for(const p of ps){const u=getUser(p.accountId);if(u){u.chips+=each;u.updatedAt=now()}}saveDB()}}room.paid=true}
function sanitizeRoom(room,uidv){tickClock(room);return{id:room.id,status:room.status,turn:room.turn,players:Object.values(room.players).map(p=>({uid:p.uid,name:p.name,side:p.side,online:now()-p.lastSeen<PLAYER_TIMEOUT})),fen:room.fen,history:room.history,clocks:room.clocks,result:room.result,winner:room.winner,drawReason:room.drawReason,lastMove:room.lastMove,moveNumber:room.moveNumber,chat:room.chat.slice(-30),stake:room.stake,bank:room.bank,selfSide:room.players[uidv]?.side||null,drawOffer:room.drawOfferBy?room.players[room.drawOfferBy]?.side||null:null,kind:room.kind,botKey:room.botKey,playerMove:room.playerMove||null,botMove:room.botMove||null,rematch:room.rematch?{deadline:room.rematch.deadline,requested:!!room.rematch.requests?.[uidv],requests:Object.keys(room.rematch.requests||{}).length}:null}}
function resetForRematch(room){
 room.status=room.kind==='online'&&Object.keys(room.players).length<2?'waiting':'playing';
 room.fen=START_FEN;room.history=[positionKey(parseFen(START_FEN))];room.turn='w';room.clocks={w:600000,b:600000};room.lastTick=now();room.lastActivity=now();room.result=null;room.winner=null;room.drawReason=null;room.lastMove=null;room.playerMove=null;room.botMove=null;room.moveNumber=1;room.drawOfferBy=null;room.paid=false;room.statsDone=false;room.rematch={deadline:0,requests:{},closed:false};
 if(room.kind==='online') room.bank=0;
}
function tryOnlineRematch(room){
 const ids=Object.keys(room.players);
 if(ids.length!==2)return false;
 if(ids.every(id=>room.rematch.requests[id])){
   for(const id of ids){const u=getUser(room.players[id].accountId);if(!u||u.chips<room.stake){room.rematch.closed=true;return false}}
   for(const id of ids){const u=getUser(room.players[id].accountId);u.chips-=room.stake;u.updatedAt=now()}
   room.bank=room.stake*2;saveDB();resetForRematch(room);return true;
 }
 return false;
}
function activeRoomPlayer(room,uidv){const p=room.players[uidv];if(!p)throw Error('Вы не участник этого стола');p.lastSeen=now();room.lastActivity=now();tickClock(room);return p}

async function route(req,res){
 const url=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=url.pathname;
 if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,version:'3.5'});
 try{
  if(req.method==='GET'&&(p==='/'||p==='/index.html'))return html(res,fs.existsSync(path.join(PUBLIC,'index.html'))?path.join(PUBLIC,'index.html'):path.join(ROOT,'index.html'));
  if(req.method==='GET'&&(p==='/style.css'||p==='/client.js')){const name=p.slice(1);const f=fs.existsSync(path.join(PUBLIC,name))?path.join(PUBLIC,name):path.join(ROOT,name);if(!fs.existsSync(f))return json(res,404,{error:'not found'});return html(res,f)}
  if(req.method==='POST'&&p==='/api/auth'){const b=await readBody(req),id=sanitizeName(b.id)||uid(),name=sanitizeName(b.name);let user=getUser(id);if(!user){if(!name)return json(res,200,{ok:true,needsName:true});user=ensureUser(id,name)}else if(name&&user.name!==name){user.name=name;user.updatedAt=now();saveDB()}if(user.banned)return json(res,403,{ok:false,error:'Пользователь заблокирован'});return json(res,200,{ok:true,user:userView(user),needsName:false,store:{boards:STORE_BOARDS,pieces:STORE_PIECES},ranks:RANKS})}
  if(req.method==='GET'&&p==='/api/state'){const u=requireUser(url.searchParams.get('uid'));return json(res,200,{ok:true,user:userView(u),store:{boards:STORE_BOARDS,pieces:STORE_PIECES},ranks:RANKS})}
  if(req.method==='GET'&&p==='/api/leaderboard'){const by=url.searchParams.get('by')==='rank'?'rank':'chips';const list=Object.values(db.users).filter(u=>!u.banned).sort((a,b)=>by==='rank'?((b.wins||0)-(a.wins||0)||(b.chips-a.chips)):b.chips-a.chips).slice(0,100).map((u,i)=>({...userView(u),position:i+1}));return json(res,200,{ok:true,by,players:list,ranks:RANKS})}
  if(req.method==='POST'&&p==='/api/shop/buy'){const b=await readBody(req),u=requireUser(b.uid),type=b.type,id=String(b.itemId||''),arr=type==='board'?STORE_BOARDS:type==='pieces'?STORE_PIECES:null;if(!arr)return json(res,400,{ok:false,error:'Неверный тип товара'});const item=arr.find(x=>x[0]===id);if(!item)return json(res,404,{ok:false,error:'Товар не найден'});const inv=type==='board'?u.inventory.boards:u.inventory.pieces;if(inv.includes(id)){if(type==='board')u.inventory.selectedBoard=id;else u.inventory.selectedPieces=id;u.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(u),selected:true,message:'Стиль выбран'})}if(u.chips<item[3])return json(res,400,{ok:false,error:'Недостаточно фишек'});u.chips-=item[3];inv.push(id);if(type==='board')u.inventory.selectedBoard=id;else u.inventory.selectedPieces=id;u.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(u),selected:true})}
  if(req.method==='POST'&&p==='/api/shop/select'){const b=await readBody(req),u=requireUser(b.uid);if(b.type==='board'&&u.inventory.boards.includes(b.itemId))u.inventory.selectedBoard=b.itemId;else if(b.type==='pieces'&&u.inventory.pieces.includes(b.itemId))u.inventory.selectedPieces=b.itemId;else return json(res,400,{ok:false,error:'Предмет не куплен'});u.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(u)})}
  if(req.method==='POST'&&p==='/api/admin/login'){const b=await readBody(req);return json(res,b.password===ADMIN_PASSWORD?200:401,{ok:b.password===ADMIN_PASSWORD})}
  if(req.method==='GET'&&p==='/api/admin/players'){if(url.searchParams.get('password')!==ADMIN_PASSWORD)return json(res,401,{ok:false,error:'Доступ запрещён'});return json(res,200,{ok:true,players:Object.values(db.users).map(userView)})}
  if(req.method==='POST'&&p==='/api/admin/action'){const b=await readBody(req);if(b.password!==ADMIN_PASSWORD)return json(res,401,{ok:false,error:'Доступ запрещён'});if(b.action==='clear_database'){db=freshDB();saveDB();rooms.clear();return json(res,200,{ok:true})}const u=getUser(b.userId);if(!u)return json(res,404,{ok:false,error:'Игрок не найден'});if(b.action==='chips'){const amount=Math.floor(Number(b.amount)||0);u.chips=Math.max(0,u.chips+amount)}else if(b.action==='vip')u.vip=!!b.value;else if(b.action==='ban')u.banned=!!b.value;else return json(res,400,{ok:false,error:'Неизвестное действие'});u.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(u)})}
  if(req.method==='POST'&&p==='/api/bot/create'){const b=await readBody(req),u=requireUser(b.uid),botKey=BOTS[b.botKey]?b.botKey:'player',stake=Math.floor(Number(b.stake));if(!Number.isFinite(stake)||stake<0)return json(res,400,{ok:false,error:'Неверная ставка'});if(stake>u.chips)return json(res,400,{ok:false,error:'Ставка превышает баланс'});u.chips-=stake;saveDB();const id=uid(),room=baseRoom(id,stake);room.kind='bot';room.status='playing';room.botKey=botKey;room.bank=stake*2;room.playerUid=id;room.players[id]={uid:id,name:u.name,side:'w',lastSeen:now(),accountId:u.id};rooms.set(id,room);return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),user:userView(u)})}
  if(req.method==='GET'&&p==='/api/bot/sync'){const room=rooms.get(String(url.searchParams.get('roomId')||'')),uidv=url.searchParams.get('uid');if(!room||room.kind!=='bot'||!room.players[uidv])return json(res,404,{ok:false,error:'Сессия не найдена'});const pl=activeRoomPlayer(room,uidv),u=requireUser(pl.accountId);return json(res,200,{ok:true,room:sanitizeRoom(room,uidv),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/bot/move'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||room.kind!=='bot'||!pl)return json(res,404,{ok:false,error:'Сессия не найдена'});const u=requireUser(pl.accountId);activeRoomPlayer(room,b.uid);if(room.result)return json(res,400,{ok:false,error:'Игра завершена'});if(room.turn!=='w')return json(res,400,{ok:false,error:'Сейчас ход компьютера'});const st=stateFromFen(room.fen,room.history),mv=parseMove(st,Number(b.from),Number(b.to),b.promotion||null);if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});let n=applyMove(st,mv);n.history=room.history.concat(positionKey(n));room.fen=fen(n);room.history=n.history;room.turn=n.side;room.lastMove=moveRecord(mv,st);room.playerMove=room.lastMove;room.botMove=null;room.lastTick=now();let status=gameStatus(n);if(!status){const bm=botMove(n,room.botKey);if(bm){const before= n;let after=applyMove(n,bm);after.history=room.history.concat(positionKey(after));room.fen=fen(after);room.history=after.history;room.turn=after.side;room.moveNumber=after.full;room.botMove=moveRecord(bm,before);room.lastMove=room.botMove;room.lastTick=now();status=gameStatus(after)}}if(status){room.result=status;room.status='finished';room.winner=status==='1-0'?'w':status==='0-1'?'b':null;room.drawReason=room.winner?'мат':'ничья';settleRoom(room)}return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/bot/resign'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||!pl||room.kind!=='bot')return json(res,404,{ok:false,error:'Сессия не найдена'});const u=requireUser(pl.accountId);activeRoomPlayer(room,b.uid);room.result='0-1';room.winner='b';room.status='finished';room.drawReason='сдача';settleRoom(room);return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/bot/rematch'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||room.kind!=='bot'||!pl)return json(res,404,{ok:false,error:'Сессия не найдена'});const u=requireUser(pl.accountId);if(!room.result)return json(res,400,{ok:false,error:'Партия ещё не завершена'});if(u.chips<room.stake)return json(res,400,{ok:false,error:'Недостаточно фишек для реванша'});u.chips-=room.stake;u.updatedAt=now();saveDB();room.bank=room.stake*2;resetForRematch(room);room.status='playing';room.rematch.deadline=now()+10000;return json(res,200,{ok:true,autoAccepted:true,room:sanitizeRoom(room,b.uid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/bot/leave'){const b=await readBody(req),room=rooms.get(String(b.roomId||''));if(room?.kind==='bot'&&!room.paid){const pl=room.players[b.uid],u=pl&&getUser(pl.accountId);if(u){u.chips+=room.stake;u.updatedAt=now();saveDB()}room.paid=true}if(room)rooms.delete(room.id);return json(res,200,{ok:true})}
  if(req.method==='POST'&&p==='/api/room/create'){const b=await readBody(req),u=requireUser(b.uid),stake=Math.floor(Number(b.stake));if(!Number.isFinite(stake)||stake<0)return json(res,400,{ok:false,error:'Неверная ставка'});if(stake>u.chips)return json(res,400,{ok:false,error:'Ставка превышает баланс'});const room=baseRoom(newRoomId(),stake);const sid=uid();room.players[sid]={uid:sid,name:u.name,side:'w',lastSeen:now(),accountId:u.id};u.chips-=stake;room.bank=stake;room.status='waiting';room.playerUid=sid;saveDB();rooms.set(room.id,room);return json(res,200,{ok:true,uid:sid,room:sanitizeRoom(room,sid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/room/join'){const b=await readBody(req),u=requireUser(b.uid),room=rooms.get(String(b.roomId||''));if(!room||room.kind!=='online')return json(res,404,{ok:false,error:'Стол не найден'});if(room.status!=='waiting')return json(res,400,{ok:false,error:'Игра уже началась'});if(Object.keys(room.players).length>=2)return json(res,400,{ok:false,error:'Стол заполнен'});if(u.chips<room.stake)return json(res,400,{ok:false,error:'Недостаточно фишек для этой ставки'});const sid=uid();room.players[sid]={uid:sid,name:u.name,side:'b',lastSeen:now(),accountId:u.id};u.chips-=room.stake;room.bank+=room.stake;room.status='playing';room.lastTick=now();room.lastActivity=now();saveDB();return json(res,200,{ok:true,uid:sid,room:sanitizeRoom(room,sid),user:userView(u)})}
  if(req.method==='GET'&&p==='/api/room/sync'){const room=rooms.get(String(url.searchParams.get('roomId')||'')),uidv=url.searchParams.get('uid');if(!room||room.kind!=='online'||!room.players[uidv])return json(res,404,{ok:false,error:'Стол не найден'});const pl=activeRoomPlayer(room,uidv),u=requireUser(pl.accountId);return json(res,200,{ok:true,room:sanitizeRoom(room,uidv),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/room/move'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||room.kind!=='online'||!pl)return json(res,404,{ok:false,error:'Стол не найден'});const u=requireUser(pl.accountId);activeRoomPlayer(room,b.uid);if(room.result)return json(res,400,{ok:false,error:'Игра завершена'});if(room.status!=='playing')return json(res,400,{ok:false,error:'Ожидание второго игрока'});if(room.turn!==pl.side)return json(res,400,{ok:false,error:'Сейчас ход соперника'});const st=stateFromFen(room.fen,room.history),mv=parseMove(st,Number(b.from),Number(b.to),b.promotion||null);if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});const n=applyMove(st,mv);n.history=room.history.concat(positionKey(n));room.fen=fen(n);room.history=n.history;room.turn=n.side;room.lastMove=moveRecord(mv,st);room.moveNumber=n.full;room.lastTick=now();const status=gameStatus(n);if(status){room.result=status;room.status='finished';room.winner=status==='1-0'?'w':status==='0-1'?'b':null;room.drawReason=room.winner?'мат':status==='1/2-1/2'?'ничья':null;settleRoom(room)}return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/room/resign'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||!pl)return json(res,404,{ok:false,error:'Стол не найден'});const u=requireUser(pl.accountId);activeRoomPlayer(room,b.uid);if(room.result)return json(res,400,{ok:false,error:'Игра завершена'});room.result=pl.side==='w'?'0-1':'1-0';room.winner=pl.side==='w'?'b':'w';room.status='finished';room.drawReason='сдача';settleRoom(room);return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/room/draw-offer'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||!pl)return json(res,404,{ok:false,error:'Стол не найден'});activeRoomPlayer(room,b.uid);room.drawOfferBy=b.uid;return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}
  if(req.method==='POST'&&p==='/api/room/draw-response'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||!pl)return json(res,404,{ok:false,error:'Стол не найден'});activeRoomPlayer(room,b.uid);if(!room.drawOfferBy||room.drawOfferBy===b.uid)return json(res,400,{ok:false,error:'Нет предложения от соперника'});if(b.accept){room.result='1/2-1/2';room.winner=null;room.status='finished';room.drawReason='соглашение';settleRoom(room)}else room.drawOfferBy=null;const u=requireUser(pl.accountId);return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),user:userView(u)})}
  if(req.method==='POST'&&p==='/api/room/chat'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||!pl)return json(res,404,{ok:false,error:'Стол не найден'});activeRoomPlayer(room,b.uid);const text=sanitizeName(b.text).slice(0,160);if(text)room.chat.push({name:pl.name,text,at:now()});return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid)})}
  if(req.method==='POST'&&p==='/api/room/rematch'){const b=await readBody(req),room=rooms.get(String(b.roomId||'')),pl=room?.players?.[b.uid];if(!room||room.kind!=='online'||!pl)return json(res,404,{ok:false,error:'Стол не найден'});activeRoomPlayer(room,b.uid);if(!room.result)return json(res,400,{ok:false,error:'Партия ещё не завершена'});if(room.rematch.closed)return json(res,400,{ok:false,error:'Реванш закрыт'});if(room.rematch.deadline&&now()>room.rematch.deadline){room.rematch.closed=true;room.rematch.deadline=0;return json(res,400,{ok:false,error:'Время реванша истекло'});}if(b.accept===false){room.rematch.closed=true;room.rematch.requests={};return json(res,200,{ok:true,accepted:false,room:sanitizeRoom(room,b.uid)})}room.rematch.deadline=room.rematch.deadline||now()+10000;room.rematch.requests[b.uid]=true;const started=tryOnlineRematch(room);return json(res,200,{ok:true,accepted:true,started,room:sanitizeRoom(room,b.uid)})}
  if(req.method==='POST'&&p==='/api/room/leave'){const b=await readBody(req),room=rooms.get(String(b.roomId||''));if(!room)return json(res,200,{ok:true});const pl=room.players[b.uid];if(!pl)return json(res,200,{ok:true});const u=getUser(pl.accountId);if(room.status==='waiting'&&!room.paid){if(u){u.chips+=room.stake;u.updatedAt=now();saveDB()}delete room.players[b.uid];if(!Object.keys(room.players).length)rooms.delete(room.id);return json(res,200,{ok:true})}if(room.status==='playing'&&!room.result&&!room.paid){const other=Object.values(room.players).find(x=>x.uid!==b.uid);if(other){room.result=pl.side==='w'?'0-1':'1-0';room.winner=other.side;room.status='finished';room.drawReason='выход из игры';settleRoom(room)}}return json(res,200,{ok:true})}
  return json(res,404,{error:'not found'});
 }catch(e){return json(res,400,{ok:false,error:e.message||'Ошибка сервера'})}
}

const cleanupTimer=setInterval(()=>{const t=now();for(const [id,r] of rooms){tickClock(r);if(r.rematch?.deadline&&r.result&&t>r.rematch.deadline){r.rematch.closed=true;r.rematch.requests={};r.rematch.deadline=0}if(t-r.lastActivity>ROOM_TTL)rooms.delete(id)}},5000);
cleanupTimer.unref?.();

function start(){const server=http.createServer(route);server.listen(PORT,'0.0.0.0',()=>console.log(`SANI CHESS 3.5 listening on ${PORT}`));return server}
if(require.main===module)start();
module.exports={parseFen,fen,legalMoves,applyMove,gameStatus,positionKey,isDead,START_FEN,start};
