const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA_DIR=process.env.DATA_DIR||ROOT,DB_FILE=path.join(DATA_DIR,'db.json');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const rooms=new Map(),botGames=new Map(),sessions=new Map(),adminSessions=new Map(),rateBuckets=new Map();
const PLAYER_TIMEOUT=15000,DISCONNECT_GRACE=60*1000,ROOM_TTL=60*60*1000,SESSION_TTL=30*24*60*60*1000,ADMIN_SESSION_TTL=8*60*60*1000;
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD;
const STORE_BOARDS=[['classic','Классика','Дерево и латунь',0],['emerald','Emerald','Изумрудный камень',30000],['midnight','Midnight','Ночной обсидиан',45000],['royal','Royal','Королевское золото',60000],['ice','Ice','Ледяной кристалл',75000],['vip_jewel','💎 Ювелирная VIP','Эксклюзивная ювелирная доска',null,'vip']];
const STORE_PIECES=[['classic','Classic','Классические фигуры',0],['neo','Neo','Современный минимализм',25000],['royal','Royal','Премиальные золотые',45000],['glass','Glass','Стеклянные фигуры',65000],['neon','Neon','Неоновый стиль',80000],['vip_gem','💎 Ювелирные VIP','Эксклюзивные ювелирные фигуры',null,'vip']];
function uid(){return crypto.randomBytes(16).toString('hex')} function now(){return Date.now()}
function json(res,code,data){const h={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; media-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",'X-Frame-Options':'DENY','Permissions-Policy':'camera=(),microphone=(),geolocation=()','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin'},sc=res.getHeader('Set-Cookie');if(sc)h['Set-Cookie']=sc;if(process.env.NODE_ENV==='production')h['Strict-Transport-Security']='max-age=31536000; includeSubDomains';res.writeHead(code,h);res.end(JSON.stringify(data))}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6){reject(new Error('Слишком большой запрос'));req.destroy()}});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(new Error('Некорректный JSON'))}});req.on('error',reject)})}
function sanitizeName(v){return String(v??'').replace(/[\u0000-\u001f\u007f<>]/g,'').replace(/\s+/g,' ').trim().slice(0,24)}
function freshDB(){return{users:{},leaderboard:[],sessions:{},rooms:{},botGames:{}}}
function loadDB(){try{const d=JSON.parse(fs.readFileSync(DB_FILE,'utf8'));return d&&d.users?d:freshDB()}catch{return freshDB()}}
let db=loadDB();
db.sessions=db.sessions&&typeof db.sessions==='object'?db.sessions:{};db.rooms=db.rooms&&typeof db.rooms==='object'?db.rooms:{};db.botGames=db.botGames&&typeof db.botGames==='object'?db.botGames:{};
for(const u of Object.values(db.users)){u.wins=Number(u.wins||0);u.losses=Number(u.losses||0);u.draws=Number(u.draws||0);u.rating=Number(u.rating||1000)}
function saveDB(){db.rooms=Object.fromEntries([...rooms].map(([id,r])=>[id,r]));db.botGames=Object.fromEntries([...botGames].map(([id,g])=>[id,g]));const tmp=DB_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DB_FILE)}
function getUser(id){return id&&db.users[id]}
function uniqueName(name,exceptId=null){const base=sanitizeName(name);if(!base)return'';const taken=new Set(Object.values(db.users).filter(u=>u.id!==exceptId).map(u=>u.name.toLowerCase()));if(!taken.has(base.toLowerCase()))return base;return''}
function ensureUser(name){const n=uniqueName(name);if(!n)throw Error('Никнейм уже занят или некорректен');const u={id:uid(),name:n,chips:100000,inventory:{boards:['classic'],pieces:['classic'],selectedBoard:'classic',selectedPieces:'classic'},vip:false,banned:false,wins:0,losses:0,draws:0,rating:1000,createdAt:now(),updatedAt:now()};db.users[u.id]=u;saveDB();return u}
function userView(u){const inv=JSON.parse(JSON.stringify(u.inventory||{boards:['classic'],pieces:['classic'],selectedBoard:'classic',selectedPieces:'classic'}));if(!u.vip){if(inv.selectedBoard==='vip_jewel')inv.selectedBoard='classic';if(inv.selectedPieces==='vip_gem')inv.selectedPieces='classic'}return{id:u.id,name:u.name,chips:u.chips,inventory:inv,vip:!!u.vip,banned:!!u.banned,wins:Number(u.wins||0),losses:Number(u.losses||0),draws:Number(u.draws||0),rating:Number(u.rating||1000),createdAt:u.createdAt,updatedAt:u.updatedAt}}
function parseCookies(req){const out={};for(const part of String(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function setCookie(res,name,value,maxAge){res.setHeader('Set-Cookie',`${name}=${encodeURIComponent(value)}; Max-Age=${maxAge}; Path=/; HttpOnly; SameSite=Lax${process.env.NODE_ENV==='production'?'; Secure':''}`)}
function clearCookie(res,name){setCookie(res,name,'',0)}
function sessionKey(token){return crypto.createHash('sha256').update(String(token)).digest('hex')}
for(const [key,s] of Object.entries(db.sessions)){if(s&&s.userId&&s.createdAt)sessions.set(key,{userId:s.userId,createdAt:Number(s.createdAt),lastSeen:Number(s.lastSeen||s.createdAt)})}
for(const [id,r] of Object.entries(db.rooms)){if(r&&r.id&&r.players&&r.fen){r.id=String(r.id);r.players=r.players||{};r.chat=Array.isArray(r.chat)?r.chat.slice(-30):[];r.history=Array.isArray(r.history)&&r.history.length?r.history:[positionKey(parseFen(r.fen))];r.revision=Number(r.revision||0);r.moves=Array.isArray(r.moves)?r.moves.slice(-500):[];r.lastTick=Number(r.lastTick||now());r.lastActivity=Number(r.lastActivity||now());r.paid=!!r.paid;rooms.set(id,r)}}
for(const [id,g] of Object.entries(db.botGames)){if(g&&g.id&&g.userId&&g.fen){g.id=String(g.id);g.history=Array.isArray(g.history)&&g.history.length?g.history:[positionKey(parseFen(g.fen))];botGames.set(id,g)}}
function persistSession(token,record){db.sessions[sessionKey(token)]=record;saveDB()}
function dropSession(token){delete db.sessions[sessionKey(token)];sessions.delete(token)}
function createSession(userId){const token=crypto.randomBytes(32).toString('hex'),record={userId,createdAt:now(),lastSeen:now()};sessions.set(token,record);persistSession(token,record);return token}
function apiError(message,status=400){const e=new Error(message);e.status=status;return e}
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim().slice(0,80)}
function allowRate(key,limit,windowMs){const t=now(),old=rateBuckets.get(key)||[];const fresh=old.filter(x=>t-x<windowMs);if(fresh.length>=limit){rateBuckets.set(key,fresh);return false}fresh.push(t);rateBuckets.set(key,fresh);if(rateBuckets.size>5000){for(const [k,v] of rateBuckets){if(v.every(x=>t-x>=windowMs))rateBuckets.delete(k)}}return true}
function currentUser(req,res){const c=parseCookies(req),token=c.sani_session,s=sessions.get(token)||db.sessions?.[sessionKey(token)];if(!s){throw apiError('Сессия не найдена',401)}if(!sessions.has(token))sessions.set(token,s);if(now()-s.createdAt>SESSION_TTL){dropSession(token);clearCookie(res,'sani_session');throw apiError('Сессия истекла',401)}const u=getUser(s.userId);if(!u||u.banned){dropSession(token);clearCookie(res,'sani_session');throw apiError(u?'Пользователь заблокирован':'Пользователь не найден',u?403:401)}s.lastSeen=now();return u}
function requireAdmin(req,res){const c=parseCookies(req),s=adminSessions.get(c.sani_admin);if(!s||now()-s.createdAt>ADMIN_SESSION_TTL)throw apiError('Доступ запрещён',401);s.lastSeen=now();return true}
function requireUserBySession(req,res){return currentUser(req,res)}
function sanitizeRoom(room,playerId){return{id:room.id,status:room.status,turn:room.turn,players:Object.values(room.players).map(p=>({uid:p.uid,name:p.name,side:p.side,vip:!!getUser(p.accountId)?.vip,online:now()-p.lastSeen<PLAYER_TIMEOUT,disconnectDeadline:p.disconnectDeadline||null})),fen:room.fen,clocks:{w:room.clocks.w,b:room.clocks.b},result:room.result,winner:room.winner,drawReason:room.drawReason,drawOffer:room.drawOffer,lastMove:room.lastMove,moves:room.moves||[],moveNumber:room.moveNumber,revision:room.revision,chat:room.chat.slice(-30),stake:room.stake,bank:room.bank,selfSide:room.players[playerId]?.side||null,forfeitReason:room.leavePlayer?`Игрок «${room.leavePlayer}» покинул стол`:room.disconnectPlayer?`Игрок «${room.disconnectPlayer}» не вернулся в течение 1 минуты`:null}}
const START_FEN='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',KNIGHT=[[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]],KING=[[1,1],[1,0],[1,-1],[0,1],[0,-1],[-1,1],[-1,0],[-1,-1]];
function fileOf(s){return s%8}function rankOf(s){return Math.floor(s/8)}function idx(f,r){return r*8+f}function colorOf(p){return !p?null:p===p.toUpperCase()?'w':'b'}function enemy(c){return c==='w'?'b':'w'}
function parseFen(f){const [placement,side,castling,ep,half,full]=f.split(/\s+/),board=Array(64).fill(null);let r=7,ff=0;for(const ch of placement){if(ch==='/'){r--;ff=0}else if(/[1-8]/.test(ch))ff+=+ch;else board[idx(ff++,r)]=ch}return{board,side,castling:castling==='-'?'':castling,ep:ep==='-'?null:ep.charCodeAt(0)-97+8*(+ep[1]-1),half:+half||0,full:+full||1,history:[]}}
function fen(st){let p='';for(let r=7;r>=0;r--){let e=0;for(let f=0;f<8;f++){const x=st.board[idx(f,r)];if(!x)e++;else{if(e){p+=e;e=0}p+=x}}if(e)p+=e;if(r)p+='/'}return`${p} ${st.side} ${st.castling||'-'} ${st.ep==null?'-':String.fromCharCode(97+fileOf(st.ep))+(rankOf(st.ep)+1)} ${st.half} ${st.full}`}
function clone(s){return{board:s.board.slice(),side:s.side,castling:s.castling,ep:s.ep,half:s.half,full:s.full,history:s.history.slice()}}function squareName(s){return String.fromCharCode(97+fileOf(s))+(rankOf(s)+1)}
function isAttacked(st,s,by){const f=fileOf(s),r=rankOf(s),pawn=by==='w'?'P':'p',pr=by==='w'?r-1:r+1;if(pr>=0&&pr<8)for(const df of[-1,1]){const F=f+df;if(F>=0&&F<8&&st.board[idx(F,pr)]===pawn)return true}const kn=by==='w'?'N':'n';for(const[dF,dR]of KNIGHT){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[idx(F,R)]===kn)return true}const ki=by==='w'?'K':'k';for(const[dF,dR]of KING){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8&&st.board[idx(F,R)]===ki)return true}for(const[dF,dR]of[[1,0],[-1,0],[0,1],[0,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[idx(F,R)];if(p){if(colorOf(p)===by&&'rq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}for(const[dF,dR]of[[1,1],[1,-1],[-1,1],[-1,-1]]){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const p=st.board[idx(F,R)];if(p){if(colorOf(p)===by&&'bq'.includes(p.toLowerCase()))return true;break}F+=dF;R+=dR}}return false}
function kingSquare(st,c){return st.board.findIndex(p=>p===(c==='w'?'K':'k'))}function inCheck(st,c){const k=kingSquare(st,c);return k<0||isAttacked(st,k,enemy(c))}
function pseudoMoves(st){const c=st.side,m=[],add=(from,to,x={})=>m.push({from,to,...x});for(let from=0;from<64;from++){const p=st.board[from];if(!p||colorOf(p)!==c)continue;const f=fileOf(from),r=rankOf(from),u=p.toUpperCase();if(u==='P'){const d=c==='w'?1:-1,sr=c==='w'?1:6,pr=c==='w'?7:0,rr=r+d;if(rr>=0&&rr<8){const one=idx(f,rr);if(!st.board[one]){if(rr===pr)for(const q of['Q','R','B','N'])add(from,one,{promotion:c==='w'?q:q.toLowerCase()});else add(from,one);if(r===sr){const two=idx(f,r+2*d);if(!st.board[two])add(from,two)}}for(const df of[-1,1]){const F=f+df;if(F<0||F>7)continue;const to=idx(F,rr),t=st.board[to];if(t&&colorOf(t)!==c){if(rr===pr)for(const q of['Q','R','B','N'])add(from,to,{promotion:c==='w'?q:q.toLowerCase()});else add(from,to)}if(st.ep===to&&st.board[to]==null)add(from,to,{ep:true})}}}else if(u==='N'){for(const[dF,dR]of KNIGHT){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t||colorOf(t)!==c)add(from,to)}}}else if(u==='K'){for(const[dF,dR]of KING){const F=f+dF,R=r+dR;if(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t||colorOf(t)!==c)add(from,to)}}const rr=c==='w'?0:7;if(from===idx(4,rr)&&!inCheck(st,c)){const K=c==='w'?'K':'k',Q=c==='w'?'Q':'q';if(st.castling.includes(K)&&st.board[idx(7,rr)]===(c==='w'?'R':'r')&&!st.board[idx(5,rr)]&&!st.board[idx(6,rr)]&&!isAttacked(st,idx(5,rr),enemy(c))&&!isAttacked(st,idx(6,rr),enemy(c)))add(from,idx(6,rr),{castle:'K'});if(st.castling.includes(Q)&&st.board[idx(0,rr)]===(c==='w'?'R':'r')&&!st.board[idx(1,rr)]&&!st.board[idx(2,rr)]&&!st.board[idx(3,rr)]&&!isAttacked(st,idx(3,rr),enemy(c))&&!isAttacked(st,idx(2,rr),enemy(c)))add(from,idx(2,rr),{castle:'Q'})}}else{const ds=u==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:u==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];for(const[dF,dR]of ds){let F=f+dF,R=r+dR;while(F>=0&&F<8&&R>=0&&R<8){const to=idx(F,R),t=st.board[to];if(!t)add(from,to);else{if(colorOf(t)!==c)add(from,to);break}F+=dF;R+=dR}}}}return m}
function applyMove(st,m){const n=clone(st),p=n.board[m.from],c=n.side,u=p.toUpperCase(),target=n.board[m.to];n.board[m.from]=null;if(m.ep)n.board[m.to+(c==='w'?-8:8)]=null;n.board[m.to]=m.promotion||p;if(m.castle){const rr=c==='w'?0:7;if(m.castle==='K'){n.board[idx(5,rr)]=n.board[idx(7,rr)];n.board[idx(7,rr)]=null}else{n.board[idx(3,rr)]=n.board[idx(0,rr)];n.board[idx(0,rr)]=null}}if(u==='K')n.castling=n.castling.replace(c==='w'?/[KQ]/g:/[kq]/g,'');if(u==='R'){if(m.from===0)n.castling=n.castling.replace('Q','');if(m.from===7)n.castling=n.castling.replace('K','');if(m.from===56)n.castling=n.castling.replace('q','');if(m.from===63)n.castling=n.castling.replace('k','')}if(target?.toUpperCase()==='R'){if(m.to===0)n.castling=n.castling.replace('Q','');if(m.to===7)n.castling=n.castling.replace('K','');if(m.to===56)n.castling=n.castling.replace('q','');if(m.to===63)n.castling=n.castling.replace('k','')}n.ep=null;if(u==='P'&&Math.abs(m.to-m.from)===16)n.ep=(m.to+m.from)/2;n.half=(u==='P'||target||m.ep)?0:n.half+1;if(c==='b')n.full++;n.side=enemy(c);return n}
function legalMoves(st){return pseudoMoves(st).filter(m=>!inCheck(applyMove(st,m),st.side))}function effectiveEp(st){if(st.ep==null)return'-';return pseudoMoves(st).some(m=>m.ep)?squareName(st.ep):'-'}function positionKey(st){return st.board.map(x=>x||'.').join('')+'|'+st.side+'|'+(st.castling||'-')+'|'+effectiveEp(st)}
function isDead(st){const ps=[];for(let i=0;i<64;i++){const p=st.board[i];if(p&&p.toUpperCase()!=='K')ps.push({p:p.toUpperCase(),s:i})}if(!ps.length)return true;if(ps.some(x=>['P','R','Q'].includes(x.p)))return false;if(ps.length===1)return true;if(ps.length===2&&ps.every(x=>x.p==='B'))return((fileOf(ps[0].s)+rankOf(ps[0].s))%2)===((fileOf(ps[1].s)+rankOf(ps[1].s))%2);return false}
function gameStatus(st){const ms=legalMoves(st);if(!ms.length)return inCheck(st,st.side)?(st.side==='w'?'0-1':'1-0'):'1/2-1/2';if(st.half>=150)return'1/2-1/2';if(isDead(st))return'1/2-1/2';const k=positionKey(st),n=st.history.filter(x=>x===k).length;return n>=5?'1/2-1/2':null}
function parseMove(st,from,to,promotion){return legalMoves(st).find(x=>x.from===from&&x.to===to&&(x.promotion||'')===(promotion||''))||null}
function moveRecord(m,st){return{from:squareName(m.from),to:squareName(m.to),promotion:m.promotion?m.promotion.toUpperCase():null}}
function stateFromFen(f,history=[]){const s=parseFen(f);s.history=history.length?history.slice():[positionKey(s)];return s}
function createRoom(stake){const s=Math.max(0,Math.floor(Number(stake)||0));let id;do{id=String(Math.floor(1000+Math.random()*9000))}while(rooms.has(id));const st=parseFen(START_FEN);return rooms.set(id,{id,status:'waiting',players:{},createdAt:now(),lastActivity:now(),fen:START_FEN,turn:'w',clocks:{w:600000,b:600000},lastTick:now(),result:null,winner:null,drawReason:null,drawOffer:null,lastMove:null,moves:[],moveNumber:1,chat:[],stake:s,bank:0,history:[positionKey(st)],revision:0,paid:false}).get(id)}
function tickClock(room){if(room.status!=='playing')return;const t=now(),dt=Math.max(0,t-room.lastTick);const turnPlayer=Object.values(room.players).find(p=>p.side===room.turn);const offline=turnPlayer&&t-turnPlayer.lastSeen>PLAYER_TIMEOUT;if(!offline){room.clocks[room.turn]=Math.max(0,room.clocks[room.turn]-dt);room.lastTick=t;if(room.clocks[room.turn]===0){room.result=room.turn==='w'?'0-1':'1-0';room.winner=room.turn==='w'?'b':'w';room.status='finished';settleWinner(room)}}else{room.lastTick=t}}
function activePlayers(room){return Object.values(room.players).filter(p=>now()-p.lastSeen<PLAYER_TIMEOUT)}
function markPlayerAlive(player){player.lastSeen=now();player.disconnectDeadline=null}
function checkRoomDisconnects(room){
  if(room.status!=='playing'||room.result)return;
  const t=now(), players=Object.values(room.players);
  for(const p of players){
    if(t-p.lastSeen>PLAYER_TIMEOUT && !p.disconnectDeadline){p.disconnectDeadline=p.lastSeen+DISCONNECT_GRACE;saveDB();}
  }
  const expired=players.find(p=>p.disconnectDeadline && t>=p.disconnectDeadline);
  if(!expired)return;
  const opponent=players.find(p=>p.uid!==expired.uid);
  if(opponent){
    room.winner=opponent.side;
    room.result=room.winner==='w'?'1-0':'0-1';
    room.drawOffer=null;
    room.status='finished';
    room.disconnectForfeit=true;
    room.disconnectPlayer=expired.name;
    settleWinner(room);
  }else{
    room.result='cancelled';room.status='finished';settleDraw(room);
  }
}
function settleWinner(room){if(room.paid)return;room.paid=true;const ps=Object.values(room.players),winner=ps.find(p=>p.side===room.winner),loser=ps.find(p=>p.side!==room.winner);const w=winner&&getUser(winner.accountId),l=loser&&getUser(loser.accountId);if(w){w.chips+=room.bank;w.wins=Number(w.wins||0)+1;w.rating=Number(w.rating||1000)+25;w.updatedAt=now()}if(l){l.losses=Number(l.losses||0)+1;l.rating=Math.max(0,Number(l.rating||1000)-18);l.updatedAt=now()}saveDB()}
function settleDraw(room){if(room.paid)return;room.paid=true;const ps=Object.values(room.players);if(ps.length){const each=Math.floor(room.bank/ps.length);for(const p of ps){const u=getUser(p.accountId);if(u){u.chips+=each;u.draws=Number(u.draws||0)+1;u.rating=Number(u.rating||1000)+3;u.updatedAt=now()}}}saveDB()}
function settleBot(g,result){if(g.settled)return;g.settled=true;const u=getUser(g.userId);if(u){if(result==='win')u.chips+=g.stake*2;else if(result==='draw'||result==='cancelled')u.chips+=g.stake;u.updatedAt=now()}saveDB()}
function finishBot(g,st,status){if(status){g.status='finished';g.result=status;settleBot(g,status==='1-0'?'win':status==='0-1'?'loss':'draw')}}function chooseBotMove(st,level){const val={P:100,N:320,B:330,R:500,Q:900,K:20000},center=[3.5,3.5];function ev(x){let score=0;for(let i=0;i<64;i++){const p=x.board[i];if(!p)continue;const c=colorOf(p),q=p.toUpperCase(),f=fileOf(i),r=rankOf(i);let v=val[q];const central=3.5-Math.abs(f-center[0])+3.5-Math.abs(r-center[1]);if(q==='N'||q==='B')v+=central*5;if(q==='P')v+=((c==='w'?r:7-r))*3;if(q==='K')v-=central*2;score+=(c==='w'?1:-1)*v}return score+(x.side==='w'?1:-1)*legalMoves(x).length*2}function mm(x,d,a,b){const ms=legalMoves(x);if(!ms.length){if(inCheck(x,x.side))return x.side==='w'?-100000:100000;return 0}if(d===0)return ev(x);if(x.side==='w'){let z=-Infinity;for(const m of ms){z=Math.max(z,mm(applyMove(x,m),d-1,a,b));a=Math.max(a,z);if(a>=b)break}return z}let z=Infinity;for(const m of ms){z=Math.min(z,mm(applyMove(x,m),d-1,a,b));b=Math.min(b,z);if(a>=b)break}return z}const depth=level===1?1:level===2?2:3,ms=legalMoves(st);let best=null,bestScore=Infinity;for(const m of ms){const sc=mm(applyMove(st,m),depth-1,-Infinity,Infinity);if(sc<bestScore){bestScore=sc;best=m}}return best}
const hintCache=new Map();
const PIECE_VALUE={P:100,N:320,B:330,R:500,Q:900,K:20000};
function evaluatePosition(st){let score=0;for(let i=0;i<64;i++){const p=st.board[i];if(!p)continue;const c=colorOf(p),q=p.toUpperCase(),f=fileOf(i),r=rankOf(i);let v=PIECE_VALUE[q]||0;const central=7-Math.abs(3.5-f)-Math.abs(3.5-r);if(q==='N'||q==='B')v+=central*4;if(q==='P')v+=(c==='w'?r:7-r)*2;score+=(c==='w'?1:-1)*v}return score+(st.side==='w'?1:-1)*legalMoves(st).length*2}
function chooseHintMove(st){const key=fen(st),cached=hintCache.get(key);if(cached)return cached;const moves=legalMoves(st);if(!moves.length)return null;const deadline=Date.now()+700,root=st.side;let timedOut=false;function search(x,d,a,b){if(Date.now()>=deadline){timedOut=true;return evaluatePosition(x)}const ms=legalMoves(x);if(!ms.length){if(inCheck(x,x.side))return x.side==='w'?-100000:100000;return 0}if(d<=0)return evaluatePosition(x);if(x.side==='w'){let best=-Infinity;for(const m of ms){best=Math.max(best,search(applyMove(x,m),d-1,a,b));a=Math.max(a,best);if(a>=b||timedOut)break}return best}let best=Infinity;for(const m of ms){best=Math.min(best,search(applyMove(x,m),d-1,a,b));b=Math.min(b,best);if(a>=b||timedOut)break}return best}
let best=moves[0],bestScore=root==='w'?-Infinity:Infinity;for(const m of moves){const score=search(applyMove(st,m),2,-Infinity,Infinity);if((root==='w'&&score>bestScore)||(root==='b'&&score<bestScore)){best=m;bestScore=score}if(timedOut)break}const result={move:moveRecord(best,st),from:best.from,to:best.to,score:bestScore};hintCache.set(key,result);if(hintCache.size>256)hintCache.delete(hintCache.keys().next().value);return result}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true});try{
if(req.method==='POST'&&p==='/api/auth'){if(!allowRate(`auth:${clientIp(req)}`,12,60_000))return json(res,429,{ok:false,error:'Слишком много запросов. Попробуйте через минуту.'});let user;try{user=currentUser(req,res)}catch{user=null}if(user)return json(res,200,{ok:true,user:userView(user),needsName:false,store:{boards:STORE_BOARDS,pieces:STORE_PIECES}});const b=await readBody(req),name=sanitizeName(b.name);if(!name)return json(res,200,{ok:true,needsName:true});user=ensureUser(name);const token=createSession(user.id);setCookie(res,'sani_session',token,SESSION_TTL);return json(res,200,{ok:true,user:userView(user),needsName:false,store:{boards:STORE_BOARDS,pieces:STORE_PIECES}})}
if(req.method==='POST'&&p==='/api/logout'){const c=parseCookies(req);if(c.sani_session)dropSession(c.sani_session);saveDB();clearCookie(res,'sani_session');return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/state'){const user=requireUserBySession(req,res);return json(res,200,{ok:true,user:userView(user),store:{boards:STORE_BOARDS,pieces:STORE_PIECES}})}
if(req.method==='POST'&&p==='/api/profile/name'){const b=await readBody(req),user=requireUserBySession(req,res),name=uniqueName(b.name,user.id);if(!name)return json(res,400,{ok:false,error:'Никнейм уже занят или некорректен'});user.name=name;user.updatedAt=now();for(const room of rooms.values()){for(const player of Object.values(room.players)){if(player.accountId===user.id)player.name=name}}saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/shop/buy'){const b=await readBody(req),user=requireUserBySession(req,res),type=b.type,id=String(b.itemId||'');const arr=type==='board'?STORE_BOARDS:type==='pieces'?STORE_PIECES:null;if(!arr)return json(res,400,{ok:false,error:'Неверный тип товара'});const item=arr.find(x=>x[0]===id);if(!item)return json(res,404,{ok:false,error:'Товар не найден'});if(item[4]==='vip')return json(res,403,{ok:false,error:'Этот предмет доступен только VIP-игрокам'});const inv=type==='board'?user.inventory.boards:user.inventory.pieces;if(inv.includes(id))return json(res,200,{ok:true,user:userView(user)});if(user.chips<item[3])return json(res,400,{ok:false,error:'Недостаточно фишек'});user.chips-=item[3];inv.push(id);user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/shop/select'){const b=await readBody(req),user=requireUserBySession(req,res),id=String(b.itemId||'');if(id==='vip_jewel'||id==='vip_gem'){if(!user.vip)return json(res,403,{ok:false,error:'Этот предмет доступен только VIP-игрокам'});if(id==='vip_jewel')user.inventory.selectedBoard=id;else user.inventory.selectedPieces=id}else if(b.type==='board'&&user.inventory.boards.includes(id))user.inventory.selectedBoard=id;else if(b.type==='pieces'&&user.inventory.pieces.includes(id))user.inventory.selectedPieces=id;else return json(res,400,{ok:false,error:'Предмет не куплен'});user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/admin/login'){if(!allowRate(`admin-login:${clientIp(req)}`,5,60_000))return json(res,429,{ok:false,error:'Слишком много попыток входа.'});if(!ADMIN_PASSWORD)return json(res,503,{ok:false,error:'ADMIN_PASSWORD не настроен на сервере'});const b=await readBody(req);if(b.password!==ADMIN_PASSWORD)return json(res,401,{ok:false});const token=crypto.randomBytes(32).toString('hex');adminSessions.set(token,{createdAt:now(),lastSeen:now()});setCookie(res,'sani_admin',token,ADMIN_SESSION_TTL);return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/admin/logout'){const c=parseCookies(req);if(c.sani_admin)adminSessions.delete(c.sani_admin);clearCookie(res,'sani_admin');return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/admin/players'){requireAdmin(req,res);return json(res,200,{ok:true,players:Object.values(db.users).map(userView)})}
if(req.method==='POST'&&p==='/api/admin/action'){requireAdmin(req,res);const b=await readBody(req);if(b.action==='clear_database'){db=freshDB();rooms.clear();botGames.clear();sessions.clear();adminSessions.clear();saveDB();return json(res,200,{ok:true})}const user=getUser(b.userId);if(!user)return json(res,404,{ok:false,error:'Игрок не найден'});if(b.action==='chips'){const amount=Number(b.amount);if(!Number.isFinite(amount))return json(res,400,{ok:false,error:'Некорректная сумма'});user.chips=Math.max(0,Math.floor(user.chips+amount))}else if(b.action==='set_chips'){const amount=Number(b.amount);if(!Number.isFinite(amount)||amount<0||amount>1000000000)return json(res,400,{ok:false,error:'Некорректное количество фишек'});user.chips=Math.floor(amount)}else if(b.action==='vip')user.vip=!!b.value;else if(b.action==='ban'){user.banned=!!b.value;if(user.banned){for(const [token,s] of sessions){if(s.userId===user.id)sessions.delete(token)}}}else if(b.action==='rename'){const name=uniqueName(b.name,user.id);if(!name)return json(res,400,{ok:false,error:'Никнейм уже занят или некорректен'});user.name=name;for(const room of rooms.values()){for(const pl of Object.values(room.players)){if(pl.accountId===user.id)pl.name=name}}}else if(b.action==='delete'){delete db.users[user.id];for(const [token,s] of sessions){if(s.userId===user.id)sessions.delete(token)}for(const room of rooms.values()){for(const [pid,pl] of Object.entries(room.players)){if(pl.accountId===user.id){pl.leftAt=now();pl.lastSeen=now();room.status='finished';room.result='cancelled';room.winner=null;room.lastActivity=now();room.revision++;if(!room.paid)settleDraw(room)}}}}else return json(res,400,{ok:false,error:'Неизвестное действие'});user.updatedAt=now();saveDB();return json(res,200,{ok:true,user:userView(user)})}
if(req.method==='POST'&&p==='/api/bot/start'){if(!allowRate(`bot-start:${clientIp(req)}`,10,60_000))return json(res,429,{ok:false,error:'Слишком много новых партий.'});const user=requireUserBySession(req,res),b=await readBody(req),stake=Math.max(0,Math.floor(Number(b.stake)||0)),level=Math.min(3,Math.max(1,Math.floor(Number(b.level)||2)));if(stake>user.chips)return json(res,400,{ok:false,error:'Недостаточно фишек для ставки'});user.chips-=stake;const id=uid(),st=parseFen(START_FEN);botGames.set(id,{id,userId:user.id,stake,level,createdAt:now(),lastActivity:now(),settled:false,status:'playing',result:null,fen:START_FEN,history:[positionKey(st)],lastMove:null});user.updatedAt=now();saveDB();return json(res,200,{ok:true,gameId:id,level,stake,user:userView(user),fen:START_FEN,result:null})}
if(req.method==='POST'&&p==='/api/bot/move'){const user=requireUserBySession(req,res),b=await readBody(req),g=botGames.get(String(b.gameId||''));if(!g||g.userId!==user.id||g.settled)return json(res,400,{ok:false,error:'Партия бота не найдена'});if(g.status!=='playing')return json(res,400,{ok:false,error:'Партия уже завершена'});let st=stateFromFen(g.fen,g.history);if(st.side!=='w')return json(res,400,{ok:false,error:'Сейчас ход компьютера'});const mv=parseMove(st,Number(b.from),Number(b.to),b.promotion||null);if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});let n=applyMove(st,mv);n.history=st.history.concat(positionKey(n));let status=gameStatus(n);const records=[moveRecord(mv,st)];if(!status){const ai=chooseBotMove(n,g.level);if(ai){const beforeAI=n;const an=applyMove(beforeAI,ai);an.history=beforeAI.history.concat(positionKey(an));n=an;records.push(moveRecord(ai,beforeAI));status=gameStatus(n)}}g.fen=fen(n);g.history=n.history;g.lastMove=records[records.length-1];g.lastActivity=now();finishBot(g,n,status);saveDB();return json(res,200,{ok:true,fen:g.fen,result:g.result,moves:records,user:userView(user)})}
if(req.method==='POST'&&p==='/api/hint'){if(!allowRate(`hint:${clientIp(req)}`,12,60_000))return json(res,429,{ok:false,error:'Подсказки временно ограничены. Попробуйте через минуту.'});const b=await readBody(req),user=requireUserBySession(req,res);if(!user.vip)return json(res,403,{ok:false,error:'Подсказка гроссмейстера доступна только VIP'});const raw=String(b.fen||'').trim();if(raw.length>200)return json(res,400,{ok:false,error:'Некорректная позиция'});let st;try{st=parseFen(raw||START_FEN)}catch{return json(res,400,{ok:false,error:'Некорректная позиция'})}if(!['w','b'].includes(st.side)||st.board.filter(Boolean).filter(p=>p==='K').length!==1||st.board.filter(Boolean).filter(p=>p==='k').length!==1)return json(res,400,{ok:false,error:'Некорректная позиция'});const h=chooseHintMove(st);if(!h)return json(res,200,{ok:true,available:false});const n=applyMove(st,legalMoves(st).find(m=>m.from===h.from&&m.to===h.to));const capture=!!st.board[h.to],givesCheck=inCheck(n,n.side),opp=legalMoves(n),mate=givesCheck&&!opp.length;return json(res,200,{ok:true,available:true,move:h.move,from:h.from,to:h.to,score:h.score,reason:mate?'Найден матовый удар.':givesCheck?'Это сильный темповый шах.':capture?'Ход выигрывает материал.':'Ход улучшает позицию и давление на ключевые поля.',threat:givesCheck?'Король соперника находится под шахом.':capture?'После хода возникает материальное преимущество.':'Сопернику сложнее защищать ключевые поля.',mateAttack:mate?'Да — найден непосредственный мат.':givesCheck?'Есть атакующая инициатива.':'Явной форсированной матовой атаки не найдено.'})}

if(req.method==='GET'&&p==='/api/leaderboard'){const players=Object.values(db.users).sort((a,b)=>Number(b.wins||0)-Number(a.wins||0)||Number(b.rating||1000)-Number(a.rating||1000)||Number(b.chips||0)-Number(a.chips||0)).slice(0,50);return json(res,200,{ok:true,players:players.map(u=>({name:u.name,chips:Number(u.chips||0),vip:!!u.vip,wins:Number(u.wins||0),losses:Number(u.losses||0),draws:Number(u.draws||0),rating:Number(u.rating||1000)}))})}
if(req.method==='POST'&&p==='/api/room/create'){if(!allowRate(`room-create:${clientIp(req)}`,10,60_000))return json(res,429,{ok:false,error:'Слишком много созданий столов. Попробуйте позже.'});const user=requireUserBySession(req,res),b=await readBody(req),stake=Math.max(0,Math.floor(Number(b.stake)||0));if(user.chips<stake)return json(res,400,{ok:false,error:'Недостаточно фишек для ставки'});user.chips-=stake;saveDB();const room=createRoom(stake),id=uid();room.players[id]={uid:id,name:user.name,side:'w',lastSeen:now(),disconnectDeadline:null,accountId:user.id};room.bank=stake;saveDB();return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),self:'w',user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/join'){if(!allowRate(`room-join:${clientIp(req)}`,20,60_000))return json(res,429,{ok:false,error:'Слишком много попыток подключения. Попробуйте позже.'});const user=requireUserBySession(req,res),b=await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase());if(!room)return json(res,404,{ok:false,error:'Комната не найдена'});if(Object.keys(room.players).length>=2||room.status!=='waiting')return json(res,400,{ok:false,error:'Комната недоступна'});if(Object.values(room.players).some(p=>p.accountId===user.id))return json(res,400,{ok:false,error:'Вы уже находитесь за этим столом'});if(user.chips<room.stake)return json(res,400,{ok:false,error:'Недостаточно фишек для ставки'});user.chips-=room.stake;const id=uid();room.players[id]={uid:id,name:user.name,side:'b',lastSeen:now(),disconnectDeadline:null,accountId:user.id};room.bank+=room.stake;room.status='playing';room.lastActivity=now();room.lastTick=now();saveDB();return json(res,200,{ok:true,uid:id,room:sanitizeRoom(room,id),self:'b',user:userView(user)})}
if(req.method==='POST'&&p==='/api/room/reconnect'){const user=requireUserBySession(req,res),b=await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase());if(!room)return json(res,404,{ok:false,error:'Комната не найдена'});const player=Object.values(room.players).find(x=>x.accountId===user.id);if(!player)return json(res,404,{ok:false,error:'Игрок не найден в этой комнате'});markPlayerAlive(player);room.lastActivity=now();saveDB();return json(res,200,{ok:true,uid:player.uid,room:sanitizeRoom(room,player.uid),self:player.side})}
const m=/^\/api\/room\/(sync|move|leave|chat|heartbeat|draw|draw-response|resign)$/.exec(p);if(m){const user=requireUserBySession(req,res),b=req.method==='GET'?Object.fromEntries(u.searchParams.entries()):await readBody(req),room=rooms.get(String(b.roomId||'').toUpperCase()),player=room?.players?.[b.uid];if(!room||!player||player.accountId!==user.id)return json(res,404,{ok:false,error:'Сессия стола не найдена'});markPlayerAlive(player);room.lastActivity=now();tickClock(room);checkRoomDisconnects(room);if(m[1]==='sync'||m[1]==='heartbeat')return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side});if(m[1]==='chat'){const recent=room.chat.filter(x=>x.uid===user.id&&now()-x.ts<10000);if(recent.length>=5)return json(res,429,{ok:false,error:'Слишком много сообщений'});const text=String(b.text||'').replace(/[<>]/g,'').slice(0,160);if(text)room.chat.push({uid:user.id,name:user.name,text,ts:now()});return json(res,200,{ok:true})}if(m[1]==='leave'){
  if(room.result)return json(res,400,{ok:false,error:'Игра уже завершена'});
  room.drawOffer=null;
  room.revision++;
  player.leftAt=now();
  player.lastSeen=now();
  player.disconnectDeadline=null;
  if(room.status==='waiting'){
    room.status='finished';room.result='cancelled';room.leavePlayer=player.name;settleDraw(room);
  }else if(room.status==='playing'){
    const opponent=Object.values(room.players).find(p=>p.uid!==player.uid);
    if(opponent){
      room.winner=opponent.side;room.result=room.winner==='w'?'1-0':'0-1';room.status='finished';room.disconnectForfeit=false;
      room.leavePlayer=player.name;
      settleWinner(room);
    }else{room.status='finished';room.result='cancelled';settleDraw(room)}
  }
  saveDB();
  return json(res,200,{ok:true,room:sanitizeRoom(room,player.uid),self:player.side})
}if(m[1]==='draw'){if(room.status!=='playing'||room.result)return json(res,400,{ok:false,error:'Игра завершена'});if(room.drawOffer)return json(res,400,{ok:false,error:'Предложение ничьей уже отправлено'});room.drawOffer={side:player.side,name:user.name,ts:now()};room.revision++;saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side})}if(m[1]==='draw-response'){if(room.status!=='playing'||room.result)return json(res,400,{ok:false,error:'Игра завершена'});if(!room.drawOffer||room.drawOffer.side===player.side)return json(res,400,{ok:false,error:'Нет предложения ничьей'});const accept=String(b.answer||'').toLowerCase()==='accept';if(accept){room.drawOffer=null;room.result='1/2-1/2';room.drawReason='По соглашению игроков';room.status='finished';settleDraw(room)}else room.drawOffer=null;room.revision++;saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side})}if(m[1]==='resign'){if(room.status!=='playing'||room.result)return json(res,400,{ok:false,error:'Игра завершена'});room.drawOffer=null;room.winner=player.side==='w'?'b':'w';room.result=room.winner==='w'?'1-0':'0-1';room.status='finished';room.revision++;settleWinner(room);saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side})}if(m[1]==='move'){if(room.status!=='playing'||room.result)return json(res,400,{ok:false,error:'Игра завершена'});if(player.side!==room.turn)return json(res,400,{ok:false,error:'Сейчас ход соперника'});const st=stateFromFen(room.fen,room.history),mv=parseMove(st,Number(b.from),Number(b.to),b.promotion||null);if(!mv)return json(res,400,{ok:false,error:'Недопустимый ход'});const n=applyMove(st,mv);n.history=st.history.concat(positionKey(n));room.drawOffer=null;const status=gameStatus(n);room.fen=fen(n);room.history=n.history;room.turn=n.side;room.moveNumber=n.full;room.lastMove=moveRecord(mv,st);room.moves=(room.moves||[]).concat(room.lastMove).slice(-500);room.revision++;room.lastTick=now();if(status){room.result=status;room.status='finished';if(status==='1-0')room.winner='w';else if(status==='0-1')room.winner='b';else room.drawReason='Правила ничьей / пат';if(room.winner)settleWinner(room);else settleDraw(room)}saveDB();return json(res,200,{ok:true,room:sanitizeRoom(room,b.uid),self:player.side})}}
}catch(e){return json(res,Number.isInteger(e.status)?e.status:400,{ok:false,error:e.message||'Ошибка сервера'})}
if(req.method==='GET'){const file=p==='/'?'/index.html':p;let fp=path.normalize(path.join(PUBLIC,file));if(!fp.startsWith(PUBLIC))return json(res,403,{error:'forbidden'});if(!fs.existsSync(fp)){fp=path.normalize(path.join(ROOT,file));if(!fp.startsWith(ROOT))return json(res,403,{error:'forbidden'})}if(!fs.existsSync(fp))return json(res,404,{error:'not found'});const ext=path.extname(fp),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.mp3':'audio/mpeg'};const cache=(ext==='.html'||ext==='.js'||ext==='.css')?'no-store':'public, max-age=3600';res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':cache});fs.createReadStream(fp).pipe(res);return}return json(res,404,{error:'not found'})}
if(require.main===module){setInterval(()=>{for(const room of rooms.values()){tickClock(room);checkRoomDisconnects(room);if(room.status==='waiting'){const owner=Object.values(room.players)[0];if(owner&&now()-owner.lastSeen>PLAYER_TIMEOUT&&!owner.disconnectDeadline){owner.disconnectDeadline=owner.lastSeen+DISCONNECT_GRACE;saveDB()}if(owner&&owner.disconnectDeadline&&now()>=owner.disconnectDeadline){room.status='finished';room.result='cancelled';room.leavePlayer=owner.name;settleDraw(room)}}if(now()-room.lastActivity>ROOM_TTL){if(!room.paid){room.status='finished';room.result='cancelled';settleDraw(room)}rooms.delete(room.id);saveDB()}}for(const [id,g] of botGames){if(now()-Number(g.lastActivity||g.createdAt)>ROOM_TTL){settleBot(g,'cancelled');botGames.delete(id);saveDB()}}for(const [t,s] of sessions){if(now()-s.lastSeen>SESSION_TTL) sessions.delete(t)}for(const [t,s] of adminSessions){if(now()-s.lastSeen>ADMIN_SESSION_TTL) adminSessions.delete(t)}},1000);http.createServer(route).listen(PORT,'0.0.0.0',()=>console.log(`SANI CHESS server: http://0.0.0.0:${PORT}`))}
module.exports={parseFen,fen,legalMoves,applyMove,positionKey,gameStatus,START_FEN,checkRoomDisconnects};
